### ISSUE TITLE
README Images

### ISSUE THREAD

**Issue by DanielOgorchock** [DanielOgorchock/ST_Anything#1]
![st_anything](https://cloud.githubusercontent.com/assets/5206084/5608219/53df3d16-944a-11e4-9791-ce42f7334990.PNG)

**Comment by ogiewon** [comment]
What did you close?

Dan

**Comment by Ledridge** [comment]
there may have been a mistake, I don't think I closed anything.

**Comment by DanielOgorchock** [comment]
I marked the issue as closed. It's the issue we use to store the readme
image. I don't think this affects anything.

On Tuesday, May 5, 2015, ogiewon <notifications@github.com> wrote:

> What did you close?
>
> Dan
>
> > On May 5, 2015, at 7:49 PM, Daniel Ogorchock <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Closed #1.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DanielOgorchock/ST_Anything/issues/1#issuecomment-99300640>
> .
>


-- 
Daniel Ogorchock

**Comment by ogiewon** [comment]
![img_1290](https://cloud.githubusercontent.com/assets/5206084/12374289/021d4434-bc65-11e5-9efa-1457365a6cd5.PNG)

**Comment by ogiewon** [comment]
![st_anything flowchart](https://cloud.githubusercontent.com/assets/5206084/25318949/d00b08b4-2865-11e7-82f6-9a355bb9082b.PNG)

**Comment by ogiewon** [comment]
![img_1942](https://cloud.githubusercontent.com/assets/5206084/25319004/8b6ab50a-2866-11e7-9f47-6f2b4863311a.PNG)

**Comment by ogiewon** [comment]
![create device manually](https://cloud.githubusercontent.com/assets/5206084/25320377/883e2d54-2874-11e7-9d7a-26774894f2c3.PNG)

**Comment by ogiewon** [comment]
![img_1941](https://cloud.githubusercontent.com/assets/5206084/25320424/f0a8f84c-2874-11e7-820e-98e2cd0ef9d2.PNG)

**Comment by ogiewon** [comment]
![image](https://cloud.githubusercontent.com/assets/5206084/26479180/53488d08-419f-11e7-824f-aa1649335c02.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36056572-6871f376-0dd3-11e8-84bc-ebfdc3d90e17.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36056703-9e743488-0dd4-11e8-8e9b-a9cfdd5a64ae.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36056798-8962892c-0dd5-11e8-90a6-c0335fb54399.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36056840-f1a188ee-0dd5-11e8-8489-18a5f35ec1ec.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36056884-510de674-0dd6-11e8-9630-a0e0fcf5b323.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36057463-77321a2c-0ddc-11e8-9fa7-ebd852307b0c.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36057621-389db756-0dde-11e8-8f8a-f1c177924a4b.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/36057659-e12352d2-0dde-11e8-98e5-db8a3b171c01.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/41034539-e3ef712e-6957-11e8-9985-5fc3cb952516.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/41034615-21f17256-6958-11e8-84cf-1f22eb7969eb.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/41034778-aeb2160a-6958-11e8-818e-0ca25a2c9f98.png)

**Comment by ogiewon** [comment]
![image](https://user-images.githubusercontent.com/5206084/41035111-a3dbac5e-6959-11e8-963c-60c33a44986c.png)

**Comment by ogiewon** [comment]
![1 - 2019-09-14 110408](https://user-images.githubusercontent.com/5206084/64909952-f4863d00-d6df-11e9-9efd-8fa541624ab3.png)
![2 -2019-09-14 110600](https://user-images.githubusercontent.com/5206084/64909953-f7812d80-d6df-11e9-884e-9aa202acfa9f.png)
