### ISSUE TITLE
DHT22 DHT Timeout Error

### ISSUE THREAD

**Issue by abdallas** [DanielOgorchock/ST_Anything#101]
I am getting a timeout error witha DHT 22 sensor.  If I use the Adafruit DHT22 library,  the sensor works fine.  Any Ideas?

**Comment by vseven** [comment]
Are you using the latest copy of the ST_Anything library?  What chip are you using?  What is the error?  Can you post a copy of your sketch?

**Comment by ogiewon** [comment]
@vseven  - This problem was discussed in the ST forum this morning and resolved.  @abdallas is using an AM2320 sensor, not a DHT22.  When a DHT22 was substituted, the problem was resolved.
