### ISSUE TITLE
433MHZ Receiver

### ISSUE THREAD

**Issue by ldrrp** [DanielOgorchock/ST_Anything#104]
ability to add 433rx receiver and individually add the id's of each sensor. These sensors are super cheap and this would be a great addition.

**Comment by ogiewon** [comment]
Feel free to add this functionality and issue a Pull Request.  I'll take a look at what you come up with.

**Comment by GeorgeHahn** [comment]
This would be pretty nice, though a little less valuable now that wifi power outlets are nearing the price of their 433MHz counterparts. What other 433MHz devices would be useful additions?

**Comment by ogiewon** [comment]
@GeorgeHahn 

ST_Anything does support 433MHz Transmitter capabilities for devices that can be controlled with the RCSwitch library.  This was quite some time ago, so I am not sure what, if anything, would need to be changed to make it work these days.

https://community.smartthings.com/t/st-anything-433mhz-rf-devices-arduino-thingshield/19084


The original poster was asking about 433MHz Receiver capabilities, which is not supported at this time.

**Comment by ogiewon** [comment]
Closing as this is not really an issue, but rather a feature request.  This should be handled by a user submitted pull request with the new code.
