### ISSUE TITLE
Help with setup // limiting child devices

### ISSUE THREAD

**Issue by tagyoureit** [DanielOgorchock/ST_Anything#105]
Hi @DanielOgorchock,
Great job on this!  I just built my first Wemos D1 mini Pro with a Relay shield and came across your library for integrating it with SmartThings.

I tested my setup with the example code for the relay shield and it works fine.  I then used your [ST_Anything_Multiples_ESP8266WIFi](https://github.com/DanielOgorchock/ST_Anything/blob/master/Arduino/Sketches/ST_Anything_Multiples_ESP8266WiFi/ST_Anything_Multiples_ESP8266WiFi.ino) with my network settings but everything else as default.

<img src="https://user-images.githubusercontent.com/1646840/35577184-c4c4a6fa-0595-11e8-9e52-ae441a491ab1.PNG" data-canonical-src="https://user-images.githubusercontent.com/1646840/35577184-c4c4a6fa-0595-11e8-9e52-ae441a491ab1.PNG" width="300"/>

This worked great and Switch 1 (sensor4) turns my relay on/off.  All of that background is just to show you it works and I am very excited at how easy it is.

My question is this - what is the proper way to limit the number of child devices to just my relay?  I've tried a number of things but this seemed the most logical.

1. In the Sketch I commented out all other devices:
```
 //*****************************************************************************
  //Add each sensor to the "Everything" Class
  //*****************************************************************************
//  st::Everything::addSensor(&sensor1);
//  st::Everything::addSensor(&sensor2);
//  st::Everything::addSensor(&sensor3);
  st::Everything::addSensor(&sensor4); 
//  st::Everything::addSensor(&sensor5); 
//  st::Everything::addSensor(&sensor6); 
//  st::Everything::addSensor(&sensor7);  
//  st::Everything::addSensor(&sensor8);  
      
  //*****************************************************************************
  //Add each executor to the "Everything" Class
  //*****************************************************************************
//  st::Everything::addExecutor(&executor1);
//  st::Everything::addExecutor(&executor2);
``` 
2.  The Wemos logging shows 1 sensor added:
```
ArduinoOTA Ready
IP address: 11.11.11.aa
ArduionOTA Host Name: ESP8266_2C3AE84aaaaaa

Everything: init ended
Everything: Free RAM = 40976
Everything: adding sensor named button1
Everything: Free RAM = 40976
Everything: initDevices started
```

3. In the config for the Device I set the number of buttons = 1.

However, no child devices are created as per the screenshot:
<img src="https://user-images.githubusercontent.com/1646840/35577349-2b1844fc-0596-11e8-8322-293d3c7ee58f.PNG" data-canonical-src="https://user-images.githubusercontent.com/1646840/35577349-2b1844fc-0596-11e8-8322-293d3c7ee58f.PNG" width="300"/>

There is also nothing of interest in the ST Logging or the Wemos logging.

I also tried setting sensor4 to sensor1 in case they needed to be added in order, but that was the same result.  Before I start trying to dig into the code and debug this myself, can you let me know if I'm barking up the right tree with my though process or if I should be trying to limit the child devices to just the switch in another method?

regards,
Tag

**Comment by tagyoureit** [comment]
Oy.  Just answered my own question, I think... I needed to uncomment the
```
 st::Everything::addExecutor(&executor2);
```

Now the switch1 shows up and changes the relay.  Thanks for the help!   🤷‍♂️

**Comment by ogiewon** [comment]
Glad you figured it out!
