### ISSUE TITLE
Feedback issue

### ISSUE THREAD

**Issue by nez91** [DanielOgorchock/ST_Anything#108]
I have successfully uploaded this to my arduino uno R3 and everything seems to be working when I have my arduino connected directly to my router using the Ethernet shield. When I move the arduino to connect to a bridge if i enable to alarm it goes through but I dont get any feedback on status of anything and I cannot turn the alarm off. I have opened ports 8090 and 39500 on my router, the bridge does not have many settings but I was able to add the mac address I assigned to the white listed devices list. When looking at wire shark looks like the protocol is arp, not sure if there is another port to open? Am I missing something here? 

Thanks!

**Comment by ogiewon** [comment]
You do not need to open any ports in your router.  The ST Hub takes care of all communications to the ST cloud servers. The Arduino only communicates to local hub. 

I am not sure what you mean by a “bridge”, but it sounds like you have a networking problem.  You mention it works if connected to the router, so at least you have everything set up correctly. Not sure how much more help I can provide.

**Comment by nez91** [comment]
I have it connected to one of these: https://www.bestbuy.com/site/tp-link-wireless-n300-wi-fi-range-extender-with-ethernet-port-white/2080012.p?skuId=2080012&ref=212&loc=1&ksid=f442889a-a16d-41a9-b04e-62d1e1d25aa8&ksprof_id=401&ksaffcode=pg264881&ksdevice=c&lsft=ref:212,loc:2&gclid=EAIaIQobChMIndGZrMuD2QIVx7bACh1q-gndEAQYASABEgIsTvD_BwE 

I can ping the arduino for some reason it doesnt seem like ST hub is also communicating to the board through the router+bridge. I'm sure its networking as well I just wasnt sure if anyone has tried something like this.

**Comment by ogiewon** [comment]
Interesting.  No one has ever mentioned using something like that.  Most users are using the NodeMCU ESP8266 boards, which have built in WiFi.

**Comment by ogiewon** [comment]
Closing as this apparently was due to the network hardware issue.
