### ISSUE TITLE
ESP8266 with Relay Shield and IC2

### ISSUE THREAD

**Issue by tagyoureit** [DanielOgorchock/ST_Anything#109]
I'm still learning all about Arduino, ESP8266, shields, etc and would appreciate some pointers/insights to see if I'm going in the right direction.

I'm using the following equipment:
1. Wemos D1 Mini Pro
1. [Relay shield](https://wiki.wemos.cc/products:d1_mini_shields:relay_shield)
1. [HC-SR501 PIR](https://www.amazon.com/HC-SR501-Sensor-Module-Pyroelectric-Infrared/dp/B007XQRKD4)
1. [Wemos OLED Shield](https://wiki.wemos.cc/products:d1_mini_shields:oled_shield)

I can get the Wemos D1 working with the relay shield and the PIR sensor.  I'm struggling a bit to incorporate the OLED shield.  

My thought process was this:
1. In ESP8266_Wifi example, I disabled everything but sensor6 (relay) and executor2 (switch)
1. I added 3 modules for the OLED shield
```
#include <Wire.h>  // Include Wire if you're using I2C
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>


  // and then Initialize WEMOS D1 mini Pro
  // D1 IO, SCL GPIO5 (original)
  // D2 IO, SDA GPIO4 (original)
  // D6 IO, GPIO12
  // D7 IO, GPIO13
  Wire.begin(12,13); //sda_pin D6 ,scl_pin D7
```
This works based on [this post](https://github.com/claws/BH1750/issues/12). 

~~Am I heading down the right path?~~ I was going to ask this, but my code is working great and all three components are acting as expected!

So my ~~next~~ question is how can I access the status of the switch/motion sensor? EG:
```
Everything: Sending: motion1 active
Everything: Sending: motion1 inactive
Everything: Received: switch1 on
EX_Switch::beSmart s = on
```
I'd like to ultimately have a timer that counts down 10 minutes since the motion sensor was last active  (probably through a WebCore Piston) and display the sensor status/time remaining on the OLED screen.  Just not really sure where to start with this one.  Is there something like `st::Everything::getStatus??` or is it better to just read the pin state directly (something like `state = digitalRead(5);`?

Thanks!
Tag

**Comment by ogiewon** [comment]
Inside the example sketches you will find the following code, which is mostly commented out.  Simply uncomment the first two lines as show below and I believe you've have what your looking for.  Just don't add any delay() statements  in your sketch as those will prefer the WiFi communications from being able to keep up with network traffic.

```
//******************************************************************************************
//st::Everything::callOnMsgSend() optional callback routine.  This is a sniffer to monitor 
//    data being sent to ST.  This allows a user to act on data changes locally within the 
//    Arduino sktech.
//******************************************************************************************
void callback(const String &msg)
{
  Serial.print(F("ST_Anything Callback: Sniffed data = "));
  Serial.println(msg);
  
  //TODO:  Add local logic here to take action when a device's value/state is changed
  
  //Masquerade as the ThingShield to send data to the Arduino, as if from the ST Cloud (uncomment and edit following line)
  //st::receiveSmartString("Put your command here!");  //use same strings that the Device Handler would send
}
```

**Comment by tagyoureit** [comment]
Awesome, thanks!  I did get this working.
