### ISSUE TITLE
EX_RGBW_Dim truncate on string to long conversion

### ISSUE THREAD

**Issue by Firemogle** [DanielOgorchock/ST_Anything#110]
I was testing with the EX_RGBW_Dim class and it looks like the conversion from the hex string to long truncates the "R" value to a maximum of 127, in my local I changed it to an unsigned long and resolved the problem.

**Comment by ogiewon** [comment]
Thanks for the feedback!  Can you please share the specifics of what file you updated, and what exact change you made?  Alternatively, you could issue a pull request to have you new version become the official new one.

**Comment by vseven** [comment]
That doesn't make much sense.  There are 4 bytes of data, R:G:B:W.  A long and a unsigned long both support 4 bytes so they should be doing the same thing.  The HEX string comes in as #AABBCCDD and the line in question is taking it from the first space (the first A) and pulling the rest out.  I'm trying to see how it could be taking "half" the Red value....

**Comment by Firemogle** [comment]
The first bit in the long is the sign bit, which causes the first chunk to effectively lose its MSB.  I tested with an R value of FF and it would always output 127.  I also tested with a full FF:FF:FF:FF and number came back as 2147483647 which is the max long value while with my change I got 4294967295, which seems more correct.

I changed:
	long number = (long) strtol( &hexstring[1], NULL, 16);
To:
	unsigned long number = (unsigned long) strtoul( &hexstring[1], NULL, 16);

and the problem went away and now FF outputs 255.

But I will say, this is the first time I have programmed in a very long time so a lot of this is rediscovery for me.  I have been modifying the code as a new class to support PCA9685 chip as I will need more I/O than my ESP8266 can handle in the future.

**Comment by vseven** [comment]
So here is the problem.  I ran a very simple program against this logic using a online C++ compiler (https://www.onlinegdb.com/online_c++_compiler in this example).  Here is my test code:

```
int
main ()
{
  int subStringR;
  int subStringG;
  int subStringB;
  int subStringW;
  string hexstring = "#FFFFFFFF";
  long number = (long) strtol (&hexstring[1], NULL, 16);
  // Split them up into r, g, b, w values
  subStringR = number >> 24;
  subStringG = number >> 16 & 0xFF;
  subStringB = number >> 8 & 0xFF;
  subStringW = number & 0xFF;
  
  cout << subStringR;
  cout << subStringG;
  cout << subStringB;
  cout << subStringW;
}
```

And here is the output:

255255255255                      

Unless there is something else going on in the Arduino compiler that I'm not understanding.

**Comment by Firemogle** [comment]
Ill test again tonight on my board.

**Comment by vseven** [comment]
Please do.  If the fix is as easy as adding "unsigned" to that line then that's fine and I'll put in a pull request to change it (or you can) but based on the above test you shouldn't have to.  Again...maybe the arduino compiler is doing something that a pure C++ compiler isn't.

**Comment by digadv** [comment]
I tested the change suggested by Firemogle and it did not resolve the problem.  I still get the results posted above.

**Comment by vseven** [comment]
I completely forgot about this until I saw the notification. I'll see what I can make of it.

**Comment by vseven** [comment]
So I also made the same change as @Firemogle and it worked:

```
Everything: Sending: rgbwSwitch1 on
Everything: Received: rgbwSwitch1 #ffffffff
EX_RGBW_Dim::beSmart s = #ffffffff
subString R:G:B:W = 255:255:255:255

```

If I had to guess you put the "unsigned" in front of both integers but missed the new **u** in strtoul from strtol.  I missed it the first time I looked at his code (should have just copied and pasted...).

**Comment by digadv** [comment]
Yep, that was it ... missed the new U.  Thanks for resolving this!  Awesome work.

**Comment by digadv** [comment]
I realize that Dan closed this issue but I'm wondering where we should discuss the PWM range of the ESP chipsets?  For example, the ESP8266 has a 10-bit range @ 1kHz.  Therefore, the 8 bit value (255 hex) does not stop the PWM (as one would read in the arduino docs) but instead produces a 25% duty cycle in the ESP8266.

**Comment by ogiewon** [comment]
That sounds like a different issue/pull request to me.
