### ISSUE TITLE
Child creation failed

### ISSUE THREAD

**Issue by sephorous** [DanielOgorchock/ST_Anything#116]
Hi,

As suggested in the title, I could not get any children to be created. Some info:

Board: Sonoff Basic ESP8266EX
Code Changes in Sketch: Only some to get pin assignments correct and some blink code to test. See attached. Any help would be appreciated. Thanks!
[sketch.txt](https://github.com/DanielOgorchock/ST_Anything/files/1820986/sketch.txt)

The following is the log.

ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: error grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'physicalgraph.device.Device' on field 'deviceNetworkId': rejected value [68C63A8B4187]; codes [physicalgraph.device.Device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique.error,device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.error.deviceNetworkId,device.deviceNetworkId.unique.error.java.lang.String,device.deviceNetworkId.unique.error,physicalgraph.device.Device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique,device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.deviceNetworkId,device.deviceNetworkId.unique.java.lang.String,device.deviceNetworkId.unique,unique.physicalgraph.device.Device.deviceNetworkId,unique.deviceNetworkId,unique.java.lang.String,unique]; arguments [deviceNetworkId,class physicalgraph.device.Device,68C63A8B4187]; default message [{0} must be unique]
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Using ip: 192.168.2.230 and port: 8090 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Executing 'refresh()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug setting deviceNetworkID = 68C63A8B4187
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Executing 'updateDeviceNetworkID'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Using ip: 192.168.2.230 and port: 8090 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:28 PM: debug Executing 'refresh()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:25 PM: debug Hub Port = 39500
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:25 PM: debug Hub IP Address = 192.168.2.140
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:25 PM: debug Executing 'updated()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:11 PM: debug Using ip: 192.168.2.230 and port: 39500 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:11 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:43:11 PM: debug Executing 'refresh()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:37 PM: debug Using ip: 192.168.2.230 and port: 39500 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:37 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:37 PM: debug Executing 'refresh()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:24 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:24 PM: debug Using ip: 192.168.2.230 and port: 39500 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:21 PM: debug Hub Port = 39500
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:21 PM: debug Hub IP Address = 192.168.2.140
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:21 PM: debug Executing 'updated()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:21 PM: debug Executing 'updated()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:03 PM: error grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'physicalgraph.device.Device' on field 'deviceNetworkId': rejected value [68C63A8B4187]; codes [physicalgraph.device.Device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique.error,device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.error.deviceNetworkId,device.deviceNetworkId.unique.error.java.lang.String,device.deviceNetworkId.unique.error,physicalgraph.device.Device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique,device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.deviceNetworkId,device.deviceNetworkId.unique.java.lang.String,device.deviceNetworkId.unique,unique.physicalgraph.device.Device.deviceNetworkId,unique.deviceNetworkId,unique.java.lang.String,unique]; arguments [deviceNetworkId,class physicalgraph.device.Device,68C63A8B4187]; default message [{0} must be unique]
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:03 PM: debug Using ip: 192.168.2.230 and port: 8090 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:03 PM: debug Executing 'refresh()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:03 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:03 PM: debug Executing 'updateDeviceNetworkID'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:03 PM: debug setting deviceNetworkID = 68C63A8B4187
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:00 PM: debug Hub Port = 39500
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:00 PM: debug Hub IP Address = 192.168.2.140
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:42:00 PM: debug Executing 'updated()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:41:49 PM: debug Using ip: 192.168.2.230 and port: 8090 for device: ea0eff65-6229-4e01-b151-a1db54ff0be1
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:41:49 PM: debug Executing 'sendEthernet' refresh
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:41:49 PM: debug Executing 'refresh()'
ea0eff65-6229-4e01-b151-a1db54ff0be1  5:41:49 PM: debug Executing 'refresh()'

**Comment by vseven** [comment]
Remove your delay statements from the sketch loop (at the bottom) then verify the MAC address is correct in the device settings.  Pretty sure the delay statements are messing it up.

**Comment by ogiewon** [comment]
Do you have two ST Parent Devices using the same MAC address?  It must be unique as it is used as the device network id.

**Comment by sephorous** [comment]
Okay so I did remove the blink/delay code, but I think it was a matter of a different ST device using the same MAC. I have been experimenting with other ESP8266 firmwares and their respective device handlers and think I re-used the same device (hence same MAC). I deleted all of those other ones re-added everything again and it works! Thanks!
