### ISSUE TITLE
Typo in EX_RGBW_Dim.cpp

### ISSUE THREAD

**Issue by digadv** [DanielOgorchock/ST_Anything#122]
Line 120 reads 	setWhitePin(pinB, channelW);

Should read 		setWhitePin(pin**W**, channelW);

**Comment by ogiewon** [comment]
Good catch!  Thank you for the feedback.  I have corrected the typo and updated the repo.

**Comment by vseven** [comment]
Truth in advertising statement:  I use, and tested, the RGB Library pretty extensively. The RGBW was a copy and paste and I asked people on the forums to try it and let me know how it worked.  Apparently no one has really used it.  Hopefully you won't find much more that I missed.
