### ISSUE TITLE
Can't get ESP8266 to show as "ThingShield"

### ISSUE THREAD

**Issue by Techno11** [DanielOgorchock/ST_Anything#123]
For another project I am working on, I need my ESP8266 to be showing up as a "ThingShield" so I can change it's device handler to something else.  How do I get it to do this?  In your SmartThings Community Post, you said that it can be done through the Arduino\Sketches\ST_Anything Sketch.  That sketch doesn't exist anymore.  Any help is appreciated!

**Comment by ogiewon** [comment]
An ESP8266 will never show up as a ThingShield. The ThingShield was discontinued by SmartThings over a year ago.  My ST_Anything library can still be used to integrate an Arduino or ESP8266 with SmartThings.  Just follow the detailed instructions in the ReadMe.  All of the code is still here.

**Comment by Techno11** [comment]
Ok. Thanks!
