### ISSUE TITLE
Custom sensor types

### ISSUE THREAD

**Issue by fishix10** [DanielOgorchock/ST_Anything#125]
I'm using ESP8266 with more than one analog sensor. So I use multiplexing (something like [this](http://www.instructables.com/id/ESP8266-with-Multiple-Analog-Sensors/)). This means that in order to poll value from A0, I have to set another pin to HIGH, then do analog read.

I'm wondering what should I do in this case with the ST_Anything library. Should I create a new device type? For example, PS_Custom_Water, with the edited getData code:

```
	void PS_Custom_Water::getData()
	{
		digitalWrite(WATER_PIN, HIGH);
		int m_nSensorValue = analogRead(m_nAnalogInputPin);
		...
```

How would the link and automatic population of sensors on the SmartThings side be affected if I created a new sensor type. I'm not sure if there's a better way... and I don't think I really understand this:

```
//******************************************************************************************
  //Declare each Device that is attached to the Arduino
  //  Notes: - For each device, there is typically a corresponding "tile" defined in your
  //           SmartThings Device Hanlder Groovy code, except when using new COMPOSITE Device Handler
  //         - For details on each device's constructor arguments below, please refer to the
  //           corresponding header (.h) and program (.cpp) files.
  //         - The name assigned to each device (1st argument below) must match the Groovy
  //           Device Handler names.  (Note: "temphumid" below is the exception to this rule
  //           as the DHT sensors produce both "temperature" and "humidity".  Data from that
  //           particular sensor is sent to the ST Hub in two separate updates, one for
  //           "temperature" and one for "humidity")
  //         - The new Composite Device Handler is comprised of a Parent DH and various Child
  //           DH's.  The names used below MUST not be changed for the Automatic Creation of
  //           child devices to work properly.  Simply increment the number by +1 for each duplicate
  //           device (e.g. contact1, contact2, contact3, etc...)  You can rename the Child Devices
  //           to match your specific use case in the ST Phone Application.
  //******************************************************************************************
```

On another note, would it be possible to specify what prefix we'd like to use for the individual sensors ("X" instead of "ST", for example).

Thanks!

**Comment by ogiewon** [comment]
Answers posted on the ST Community Forum at 

https://community.smartthings.com/t/release-st-anything-v2-9-arduino-esp8266-esp32-to-st-via-thingshield-ethernet-or-wifi/77707/1487?u=ogiewon
