### ISSUE TITLE
SmartThingsESP8266WiFi::send(String message) taking about 30 seconds to respond...

### ISSUE THREAD

**Issue by tobzking** [DanielOgorchock/ST_Anything#127]
I have been successfully using ST_Anything for a few weeks. In the last few days, since I connected a second hub in another location, all my ST_Anything devices are not responding. Tracing this through the code, 
there is a 30 delay in running the st_client.println command in SmartThingsESP8266WiFi::send(String message).
This results in my loop running every 30 seconds or so which of course means that it appears that everything hangs...
Any ideas?

**Comment by ogiewon** [comment]
I have never heard of the problem you are describing.  That st_client.println is part of the routine that actually sends out the LAN packet to your ST Hub.  Are you sure that the LAN address of your hub hasn't changed at all?

**Comment by tobzking** [comment]
Very strange. Hub could be pinged, zwave, zigbee and other wifi based technology working but ST_Anything wasn't.
A good old fashioned reboot of the Hub fixed it... which I wish I had done yesterday!

**Comment by ogiewon** [comment]
Glad a hub reboot solved it!
