### ISSUE TITLE
SmartThingsESP32WiFi send() can get stuck in loop with st_client.read

### ISSUE THREAD

**Issue by mlampkin** [DanielOgorchock/ST_Anything#128]
The following is being seen when using a HiLetgo ESP-WROOM-32 ( new ) and a SmartThings v2 hub with most recent firmware updates.

After POSTING status to hub, current code looks for a response with the following:

while (st_client.connected()) {
  char c = st_client.read();
}

Any error on read e.g. the hub closing the connection after receiving the POST - the local socket is remaining open / showing itself as connected and read is returning "data" that is actually a -1 / (int) 255 error.   That is - execution becomes trapped in the loop until the heat death of the universe.

Adding a check for read returning a -1 / (int) 255 and executing a break out of the loop fixes the issue.

**Comment by ogiewon** [comment]
Good info.  Thank you!  Can you please post the code snippet with your fix included?

**Comment by mlampkin** [comment]
Kids and their friends tonight - sleepover -  full house and no time.  I'll
do a real pull ( just did a local download ) and push the fix hopefully
tomorrow or Friday.

I think it is an artifact of the firmware update earlier this year i.e.
smarthub doesn't appear to be sending a http reply ( and could have sworn
it was last year / last time I checked ).  I doubled checked hitting the
port with various programs - not just st_anything - and seeing the same
thing.

Michael

**Comment by mlampkin** [comment]
In the send functioin around line 313 or so...

Change post to tell the server to close the connection after we send our msg i.e. let it know we aren't going to try to chain requests on this connection.

Change message send to not include cr ln so our message size is correct.

`			st_client.println(F("POST / HTTP/1.1"));
			st_client.print(F("HOST: "));
			st_client.print(st_hubIP);
			st_client.print(F(":"));
			st_client.println(st_hubPort);
			st_client.println(F("CONTENT-TYPE: text"));
			st_client.println(F("CONNECTION: CLOSE"));
			st_client.print(F("CONTENT-LENGTH: "));
			st_client.println(message.length());
			st_client.println();
			st_client.print(message);`

Change loop back to checking if data is available to read in socket input buffer.  It seems the ST hub with current firmware always just closes without a response - not even an OK response.  This means we will always see "connected" but should not see "available" and the loop should ( at this time / current firmware ) not execute.

Line 375 or in that general vicinity...

Just in case that changes and next firmware sends a response, read it out of the buffer and break out of loop when we see an errno -1 on a read.

`		while (st_client.available()) { // connected()) {
			//while (st_client.available()) {
			char c = st_client.read(); //gets byte from ethernet buffer
									   //if (_isDebugEnabled) { Serial.print(c); } //prints byte to serial monitor
									   //}
			if ( (int) c == 255 ) break;
		}`

Sorry guys - really busy and was going to do the entire file but right now I'm on my phone doing this... hopefully it isn't too scrambled to understand.

**Comment by ogiewon** [comment]
Thanks for your help!  Fix has been pushed.  Please grab latest SmartThingsESP32WIFI.cpp.
