### ISSUE TITLE
Ardunio with smart things controlling 2 outputs

### ISSUE THREAD

**Issue by rhfarmer9012** [DanielOgorchock/ST_Anything#13]
I'm having trouble with getting 2 outputs to work on the ardunio from the ST mobile platform.  I'm not a programmer but I'm pretty certain that my code is correct.  I think my trouble is in the device handler.  Is it possible to have 2 outputs controlled by the same device handler?  I can easily get one or the other to work but not both at the same time.  I diffidently don't completely understand how the communication works between the mobile platform to the hub to the ardunio.

metadata {
	definition (name: "Randall Shield", namespace: "smartthings", author: "SmartThings") {
		capability "Actuator"
		capability "Switch"
		capability "Sensor"
	}

	// Simulator metadata
	simulator {
		status "on":  "catchall: 0104 0000 01 01 0040 00 0A21 00 00 0000 0A 00 0A6F6E"
		status "off": "catchall: 0104 0000 01 01 0040 00 0A21 00 00 0000 0A 00 0A6F6666"

		// reply messages
		reply "raw 0x0 { 00 00 0a 0a 6f 6e }": "catchall: 0104 0000 01 01 0040 00 0A21 00 00 0000 0A 00 0A6F6E"
		reply "raw 0x0 { 00 00 0a 0a 6f 66 66 }": "catchall: 0104 0000 01 01 0040 00 0A21 00 00 0000 0A 00 0A6F6666"
	}

	// UI tile definitions
	tiles (scale: 2){
		standardTile( "switch", "device.switch", width: 3, height: 3, canChangeIcon: true, canChangeBackground: true) {
		state "on", label: 'On', action: "switch.off", icon: "st.switches.switch.on", backgroundColor: "#79b821"
		state "off", label: 'Operate Right Door', action: "switch.on", icon: "st.switches.switch.off", backgroundColor: "#ffffff"
		}
        
       standardTile( "switch2", "device.switch", width: 3, height: 3, canChangeIcon: true, canChangeBackground: true) {
		state "onr", label: 'On', action: "switch.off", icon: "st.switches.switch.on", backgroundColor: "#79b821"
		state "offr", label: 'Operate Left Door', action: "switch.on", icon: "st.switches.switch.off", backgroundColor: "#ffffff"
		}
        

		standardTile("contact", "device.contact", width: 3, height: 3) {
			state "open", label: '${name}', icon: "st.contact.contact.open", backgroundColor: "#ffa81e"
			state "closed", label: '${name}', icon: "st.contact.contact.closed", backgroundColor: "#79b821"
		}
		
        standardTile("contact", "device.contact", width: 3, height: 3) {
			state "open", label: '${name}', icon: "st.contact.contact.open", backgroundColor: "#ffa81e"
			state "closed", label: '${name}', icon: "st.contact.contact.closed", backgroundColor: "#79b821"
		}

		main "switch"
		details  "switch" , "switch2", "contact" , "contact2" 
	}
}

// Parse incoming device messages to generate events
def parse(String description) {
	def value = zigbee.parse(description)?.text
	def name = value in ["on","off"] ? "switch" : null
	def result = createEvent(name: name, value: value)
	log.debug "Parse returned ${result?.descriptionText}"
	return result
}

// Commands sent to the device

def on() {
	zigbee.smartShield(text: "on").format()
}

def off() {
	zigbee.smartShield(text: "off").format()
}

def onR() {
	zigbee.smartShield(text: "onr").format()
}

def offR() {
	zigbee.smartShield(text: "offr").format()
}

**Comment by ogiewon** [comment]
Why not just use ST_Anything library and examples as a starting point, versus the lower level SmartThings library?  The latest version uses the new ST Composite Device Handler which greatly simplifies the Groovy side of writing code. In fact, most users will not need to write any groovy code!

Your current Device Handler code will not work as written. Your Actions for Switch2 need to call your OnR and OffR functions.

**Comment by ogiewon** [comment]
No reply in 2 months.  Closing the issue.
