### ISSUE TITLE
Samsung Connect (New App) Cannot Set Device Prefs. (No childDeviceCreation)

### ISSUE THREAD

**Issue by mkreafle** [DanielOgorchock/ST_Anything#135]
I just want to preface this with: I am sorry, and I know this is not an issue with your project but seems to be one with the new application.

> On your ST Mobile App, after you manually create a ST_Anything Parent Ethernet Device, be sure to configure the settings, including the number of buttons to match your desired number of keypad buttons. NO CHILD DEVICE WILL BE CREATED for buttons. You simply point any SmartApp at the Parent Device to subscribe to the button pushed events.

Problem seems to be I cannot figure out how to do this with the new App. I can do it from the website after I create the device, but this never seems to re-trigger "childDeviceCreation" and I was hoping someone here would have a fix or work around.

Please, feel free to close this ticket if I am being silly.
Thanks!
--Mark

**Comment by vseven** [comment]
So the Samsung Connect app is **_awful_**.  Its incomplete and barely functional.  It does NOT currently work with Konnected, ST_Anything, and many other 3rd party apps and devices.  Hell they just added the ability to dim lights a couple weeks ago.

Don't use it.  Stick with the SmartThings Classic app until they put out something usable.

**Comment by mkreafle** [comment]
Thanks. 
:(
Turns out that was the "fix" I was expecting. ;)
