### ISSUE TITLE
Stuck at Smartthings IDE Setup

### ISSUE THREAD

**Issue by fiz1962** [DanielOgorchock/ST_Anything#137]
I created an account at https://smartthings.developer.samsung.com/ and logged in.  But I get stumped at "Click on My Device Handlers".  I've poked around the website but can't find anything that looks remotely like any of the instructions beyond that.  I do find a page with a "Coming Soon" that makes me wonder if the Smartthings site is being rewritten?

https://smartthings.developer.samsung.com/develop/getting-started/hub-connected.html

SmartThings IDE Setup Instructions

OK ->    Create an account and/or log into the SmartThings Developers Web IDE.
??? ->    Click on "My Device Handlers" from the navigation menu.

**Comment by DanielOgorchock** [comment]
Login here: https://graph.api.smartthings.com/

You have to use the SmartThings classic IDE.
