### ISSUE TITLE
Events and groovy

### ISSUE THREAD

**Issue by ericterstegen** [DanielOgorchock/ST_Anything#138]
I am almost done with my roller shades project.  Using a esp32 with a cheap 2 channel motor driver to pull two roller shades down with an ir sensor at the top to detect open/close and timing to set how long to leave the motor on to close (open uses the sensor since it is at the top).  Right now I am using a generic executor type with just the switch capability.  I also have physical buttons (up and down) that can be used in lieu of ST.  

With all that said I have updates running well to the main tile but have issues with the "config" tile.  The config tile goes from "config" to "startCfg" fine since I have the nextState set (this is to prep the user).  But once the startCfg is pressed it sends to the esp32 fine and the motor starts going but I cannot get the state back to the tile from esp32 to move to "stopCfg".  When I send things like "opening" and "closed" from my esp32 the main tile updates fine.  But when I send "startCfg" or "stopCfg" from the esp32 it does not update the config tile to the appropriate state.

My understanding of how the sendSmartString works is very hazy.  When the esp32 sends a command with that function how does the hub/groovy code interact with it?  Is that setting "state" or running a groovy function?  I thought it would link to states since that seems to happen with the main tile...

The Samsung docs regarding this seem lacking but maybe I am not looking in the right place. 

Thanks!

[rollershade.groovy.txt](https://github.com/DanielOgorchock/ST_Anything/files/2172941/rollershade.groovy.txt)

**Comment by ogiewon** [comment]
Just a quick FYI...  I have recently updated all of the Parent and Child Device Handlers in my GitHub repository.  If you upgrade these DTH’s, your custom Child Device Handler will also need to be modified. 

The basic data flow (new DTH’s) is ESP32 to Hub, Hub to Cloud Parent Device, Parent Device to Child Device’s parse() routine.  Within the parse() routine you’ll see a sendEvent(name: ... , value: ...) call. The name variable must match an Attribute.  You appear to be using custom attributes.  You may want to instead use the standard Capability for window shade.  If you do, you need to stick to values that match the standard values described in the ST Classic Capabilities Reference documentation.

**Comment by elfege** [comment]
ok, dumb question among the dumbest questions: How do you get to send a command from ST virtual device to ESP32? In the ESP8266 there's the messageCallout() function but how do you get the same result with ESP32? callback seems to only a sniffer/simulator of that purpose and executors seem to have to be directly related to pins while there are commands I need to send and that are not related to controlling any pin... 

Thank you in advance.
