### ISSUE TITLE
Endpoints questions

### ISSUE THREAD

**Issue by edasque** [DanielOgorchock/ST_Anything#140]
More out of curiosity than anything, am I right in assuming that these sketches add some endpoints hosted by HTTP on the device (at default port 8090).

If so, is there a documentation of the endpoints, that could maybe help one debug things or used them for something else. Another related question is whether I can use those endpoints to provide some sort of a health check.

If not, how would you add endpoints?

**Comment by edasque** [comment]
Great to understand the history. And to be clear, I was just being curious, this works really well for me on ST and my three devices (2 temp, one RGB LED).

I'll have a few other questions, they're not issues but advice on implementing a RGBw device where the code to change colors might be a little different from the standard. Should I ask here or is there a better place to do so (forum, gitter, ...)

**Comment by vseven** [comment]
You can message me on the SmartThings forums (same username).  I wrote the RGB and RGBW libraries so hopefully I can help.

**Comment by edasque** [comment]
@vseven I appreciate it. I got it working great with a single LED but it wasn't bright enough so I bought a few alternatives that are on the way, some of which have a whole library to control them. I'll reach out when I've researched it a bit more. Thanks for offering your help.
