### ISSUE TITLE
ArduinoOTA not working 

### ISSUE THREAD

**Issue by elfege** [DanielOgorchock/ST_Anything#142]
Hi, 
ArduinoOTA not working seems to be incompatible with ST_Anything libraries on ESP32. When I comment out all ST related code, it works again on ESP32. 

Do you have any idea what might cause this and if there's a way to work around this issue? 

Thank you very much. 
EL

**Comment by elfege** [comment]
It's now working but I can't damn remember what was wrong nor how I fixed it! LOL...

**Comment by ogiewon** [comment]
I don’t recall ever adding ArduinoOTA functionality to the ESP32 platform.  Just the ESP8266 has it, unless I am remembering wrong...
