### ISSUE TITLE
lwIP problem and solution

### ISSUE THREAD

**Issue by fiz1962** [DanielOgorchock/ST_Anything#143]
I'm using

WeMos D1 R2 & mini (ESP8266 variant)
Arduino IDE 1.8.5
ESP8266 lib v2.3.0

My devices are "disappearing" after 8-9 hours and I seem to have it tracked down to a new Option under the Tools menu in the Arduino IDE, or at least an option that I've never changed in the past.  This may be related to the v2.4.0 lib issue, even when using v2.3.0.  Compiling with the  "Tools/lwIP variant" option set to v2 causes my device to disappear (likely just the TCP stack crashes) after 8-9 hours.  The solution seems to be to use lwIP variant "v1.4 Higher Bandwidth".  So far my devices have ran reliably after switching this option.

**Comment by fiz1962** [comment]
Upate.

WeMos mini board (ESP8266 variant)
Arduino IDE 1.8.5
ESP8266 v2.3.0

I have a doorControl using the above board with a magnetic switch and relay.  It was compiled with an older version of the IDE but the same ESP8266 libs.  I've lost track but believe it has ran for 2-3 weeks without problem.

I have been trying to build 2 PIR motion boards unsuccessfully.  I believe I updated the Arduino IDE since building the doorControl.  If I compile with the Tools/lwIP option set to v2 (IDE 1.8.5), both motion boards fail after 8-9 hours.  I thought I had it fixed by switching to lwIP v1.4 and they do run longer, but the 2 boards failed after approx 36 & 40 hours.

**Comment by fiz1962** [comment]
Here's what I've found from 2 motion boards using a WeMos D1 mini, esp8266 lib v2.3.0 and various Arduino IDE versions.

IDE 1.8.5 lwIP v 2 - crashes after 8-9 hours
IDE 1.8.5 lwIP v 1.4 - crashes after 36-40 hours
IDE 1.8.4 - 2 motion boards running for 72 hours and haven't failed yet

**Comment by ogiewon** [comment]
Very interesting.  Thanks for sharing your findings.  I have never noticed that setting either.

**Comment by fiz1962** [comment]
lwIP was apparently added in IDE v1.8.5 and a search suggests it is related to the ESP8266 v2.4.0 problem, possibly even with ESP8266 lib v2.3.0.

Happily, going back to IDE v1.8.4 seems to have fixed the problem.  I've lost track of when my doorControl was last rebooted (2-3 weeks ago to make a wiring change?) and my Motion detectors are coming up on 96 hours with no problems.

**Comment by ogiewon** [comment]
FYI - I have recently tested an ESP8266 using Arduino IDE 1.8.8 and ESP8266 v2.4.2, using all three precompiled variants of IwIP.  I could not reproduce the memory leak with this new combination.  Hoepfully that issue is now behind us all for good!
