### ISSUE TITLE
Idea: Garage Door Controller

### ISSUE THREAD

**Issue by Techno11** [DanielOgorchock/ST_Anything#145]
Combine the use of a contact sensor (or contact sensors) and a Digital Input/Output to control a "dumb" garage door opener.  There are other ways to do this, however none that I can find that are able to track if the garage door is open or closed.

**Comment by ogiewon** [comment]
This device class already exists as the Door Control. You can see an example of it in one of the Arduino Mega sample sketches.

**Comment by Techno11** [comment]
My bad, Thanks for clarifying!
