### ISSUE TITLE
Motion only works on USB

### ISSUE THREAD

**Issue by kkennemore** [DanielOgorchock/ST_Anything#146]
Having weird issue where, as long as it is connected to computer via USB, everything works great.  As soon as I try to run it stand alone the motion sensors quit updating.  Relays respond just fine to button pushes on the ST app, it is just that the motion quits receiving updates.  Odd thing is, if I manually pull the sensor wire from the breadboard and create my own circuit interruption, it works fine.  The interruption caused by the separately powered motion sensor only works when connected with USB.  The serial monitor does not have to be open, just connected.  
Has anyone run into this?
Thanks

**Comment by vseven** [comment]
You sure its not a power issue?  I.e. try powering your board with a different source.

**Comment by ogiewon** [comment]
If you power the board via USB using a phone charger, does it work?  

Need more details of what board you’re using and how you have everything wired up to it.

**Comment by kkennemore** [comment]
Thank you for your prompt response.  The phone charger is a good idea.  I tried it but there was no change in behavior.  I have a mega connected to a w5100 shield. I have reduced my setup to nothing but a motion sensor.  I have a constant high on the input pin, when it drops from the motion sensor interrupting the circuit it triggers.  When connected to my computer (I don't even have to have serial monitor open), it will update smartthings app on my phone instantly as soon as the motion sensor clicks.  If I unplug the USB, or plug it into the phone charger the phone app stops updating when motion is sensed.  If I manually pull the wire from the pin to cause the interrupt it works.  I can't figure that one out.  Also, what may be of help is that when the motion does work on the app it goes back and forth quickly from active to inactive.
Thanks again for your help.  Your project is exactly what I am looking for!

**Comment by kkennemore** [comment]
Also, when not connected to USB, the ST IDE live log is receiving the periodic refreshes.  It does show the motion active events but as before, only with USB connected to computer.

**Comment by kkennemore** [comment]
Got It!  This my first project with arduino.  I had 5v going through the circuit and the pin set to detect the lack of.  I looped it to ground and set the pin accordingly with pullup to true and it works great.  Thank you for taking the time to help.  Great project.  Take care.
