### ISSUE TITLE
MEGAWiFiEsp : I'm lost for I don't know what I'm supposed to do on the ESP01 module part

### ISSUE THREAD

**Issue by elfege** [DanielOgorchock/ST_Anything#150]
Ok, so I think I've wired both atmega2560 and ESP01 properly. What I can't figure out is what I'm supposed to do on the ESP part. Surely the module has to be uploaded with some code to be able to communicate with the arduino atmega2560, no? .

So far this is what I get: 
Everything: init started
Everything: Free RAM = 5017

Initializing WiFiEsp network.  Please be patient...
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Cannot initialize ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
ESP WiFi shield not present

What sketch is the ESP01 supposed to be written with to work with MEGAWiFiEsp ? 

Everywhere I look, i can't find any indication it is needed, just as if the firmware were to handle the ESP01 on its own to interact with MEGAWiFiEsp requests... 

Obviously, there's something I'm not getting... can someone help me with this ?

Thanks

**Comment by ogiewon** [comment]
The ESP01 modules ship with “AT Firmware” that supports serial communications to implement WiFi connectivity. The ESPWiFi library uses this serial communications to implement an Arduino compatible library that mimics other WiFi API’s.  

ST_Anything example sketches assume you wire the ESP01 to the MEGA’s “Serial1” hardware UART pins.  

It is assumed that the user already has experience using an ESP01 with an Arduino before attempting to use ST_Anything with it.  Also, I typically advise users to try running ST_Anything directly on a NodeMCU ESP8266 board as it is much more reliable.

**Comment by elfege** [comment]
Thank you. I eventually figured it out and came back here to delete my question but you had answered it already. I suppose you haven't figure out the stability issues since then? Couldn't it be a power issue? I've seen guys online adding some resistors and a 10uF capacitor... dunno if this could help, I'll try and let you know if by chances it solves the issue. Let me know, also, if you figured it out. 

Here is a video by a guy who doesn't seem to have such issues: 

// https://www.youtube.com/watch?v=YLKEZtLhfZo video that explains everything about this
// https://www.electrodragon.com/w/File:At_firmware_bin1.54.zip FIRMWARE (I added this to the comments in your sketch because I want to remember this next time so I don't bother you again! :) ) 

thanks again

**Comment by elfege** [comment]
By "stability issue" I actually mean something different from what you discussed in another thread. I now can connect my Mega2560 to the wifi through ESP01 but I get the "**** WiFi Disconnected.  ESP8266 should auto-reconnect ****" message every 4 seconds or so. Have you seen this happening in the past? Thanks. (FYI I have countless of sensors an other smart devices working with your ST_Anything library).

**Comment by ogiewon** [comment]
I was never able to get it to stay connected to WiFi reliably. If you figure out a solution, I’m all ears.

**Comment by elfege** [comment]
Well, I did it, it seems. But this is mainly because I'm not using all the libraries. Here are those I'm exlusively using for now, and it seems stable: 

I don't know if it's related, but maybe it can set us on the right track. Maybe you can try to use only those libraries and if it is also stable, then it will allow you, bit by bit, to narrow down which one is causing the instability. Hope this helps. 

#include <math.h>
#include <Streaming.h>      // Ref: http://arduiniana.org/libraries/streaming/
#include <IRremote.h>

//******************************************************************************************
// SmartThings Library for Arduino + ESP-01 board combination.
//******************************************************************************************
#include <SmartThingsWiFiEsp.h>    //Library to provide API to the SmartThings ESP-01 WiFi board
#include <Everything.h>      //Master Brain of ST_Anything library that ties everything together and performs ST Shield communications
#include <Executor.h>        //Generic Executor Class, typically receives data from ST Cloud (e.g. Switch)

**Comment by elfege** [comment]
Now I'm trying to get the webserver() to work. All my ST_Anything devices have a webserver on port 8888 so I can also use a web browser to control/check/reset them if necessary. The project I'm working on right now is a rover that used to work on ESP32 but I've reached its limits in terms of GPIOS. Using a webpage is crucial for tests on this one. If you have any idea how I can get to display a webpage. for now calling for WiFiEspServer server(8888) compiles but no response in the browser. I suppose it's that I have to go through the Serial1, probably using st namespace but I haven't figured how yet. Let me know you can help me on this one. Thanks.
