### ISSUE TITLE
Has anyone lost all their ESP8266 at once as of Thursday? 

### ISSUE THREAD

**Issue by elfege** [DanielOgorchock/ST_Anything#151]
Since last firmware upgrade on ST's HUB, all my ESP8266 based smart devices, using DanielOgorchock's Libraries, went down, and only those. ESP32's devices seem to have not been affected, but for what regard ESP8266's, there's seem to be no exception. They all boot, but after a couple minutes they stay stuck. Reflashing did nothing... 

Let me know.

**Comment by ryancasler** [comment]
Why would the hub firmware update cause your ESP's to not boot?  Or hang at some point?  Mine are working fine.

**Comment by elfege** [comment]
Yeah I figured it was a stupid question at first but all my esp’s were unresponsive even after reloading them / replacing them / flashing them... all of them now exception... was one of these days when nothing makes sense. In the end it turned out to be the hub since a simple reboot fixed te problem! Dunno what was going on but it was directly related to communication with ST... for some reason the library would not timeout... 

Elfège Leylavergne

**Comment by ogiewon** [comment]
Glad to hear a simple hub reboot fixed it.
