### ISSUE TITLE
Child Devices Not Auto Creating

### ISSUE THREAD

**Issue by breezer260** [DanielOgorchock/ST_Anything#153]

**Comment by ogiewon** [comment]
That’s not much information to go on...  Follow the ReadMe exactly, and the child devices will be automatically created.

**Comment by breezer260** [comment]
So sorry, I figured it out, I thought I hit cancel... My apologies, again
thank you so much for your work.

I do have another issue.  The servos do work with the starting angle at
zero, but any value I slide in the smartthings app will force the servo to
go all the way to 180 degrees and it will get stuck there.  I thought maybe
a bad servo so I tried another one but same outcome.

For example:

The servos are tower pro sg-5010 and when I use the

Servo.write (value) it works as expected rotating 0 to 180 and 180 to 0 as
desired from the example sketch.

Using your mapping, the servos only go from 0 to 180.  I cannot get them to
rotate back to zero and move the proper amount.  50% should be 90 degrees
but that doesn't happen.  I've also added true after the starting angle to
cut power after the movement hoping that would fix but no avail.

Again, you're work is amazing, I'm trying to read as much as I can to learn
how to do this.

I'm using a Nodemcu btw if that makes a difference.

Joe

**Comment by ogiewon** [comment]
When you declare the ST_Anything Servo object, what does that line of code look like?

**Comment by breezer260** [comment]
I haven't changed anything in your code other than the wifi information
that is required to connect to smartthings and added "true" to the code
after starting angle.

So the declaration are exactly what they are in your servo example sketch.
D1/GPIO 5 is the pin that I'm using, I believe.

I'm not sure if I'm answering your question properly, so let me know.

Joe

**Comment by ogiewon** [comment]
The problem you’re having is strange...  I have no problem controlling a very small inexpensive servo via a NodeMCU ESP8266 Board. I can pick any dimmer level from 0 to 100 and the servo immediately follows from 0 to 180 degrees. I don’t have larger servos to try.  My code simply uses the standard Arduino Servo library.  There is very little to it other than mapping 0-100 to 0-180.

**Comment by breezer260** [comment]
Thank you for checking it on your end, I've tried different power supply
for the servos and that didn't help.

Finally, I just started the wiring process all over and now everything
works perfectly! There must've been a short somewhere that I missed.  Thank
you for your help.  Feel free to delete this entire issue as it was all my
fault.

Can't wait to use your other sensors and devices.
