### ISSUE TITLE
Compatibility with new Smartthings app?

### ISSUE THREAD

**Issue by lestrauss** [DanielOgorchock/ST_Anything#156]
I'm wondering whats needed to integrate ST_Anything with the new Samsung Smartthings App?

**Comment by vseven** [comment]
Some updates to each DTH but since SmartThings hasn't release any official documentation any changes would be educated guesses and may or may not work now or in the future.  

For example iade a modified contact DTH which is working well but that might change.

**Comment by lestrauss** [comment]
That's what I guessed trying to find an answer reading their documentation, the only conclusion I got was those docs are far from complete.

It's funny though cause they released some documentation on creating Directly Connected devices but it's only for super specific hardware, using super specific software.

**Comment by ogiewon** [comment]
Correct.  We’re all still waiting for Hub connected device documentation...

**Comment by vseven** [comment]
If you really want to play you can look at my modified contact sensor:

https://github.com/vseven/SmartThings_VSeven/blob/master/devicetypes/vseven/child-contact-sensor-enhanced.src/child-contact-sensor-enhanced.groovy

You'll see some extra meta data that makes the contact sensor work.  Something like that needs to be done to each DTH but there is no clear documentation on how to do it.  So people, myself included, have just been looking at what SmartThings is doing to the official DTH's and then modifying custom to match.

**Comment by lestrauss** [comment]
I will surely have a look, in fact I just might have or haven't taken a look after your first comment :stuck_out_tongue_winking_eye: 

Where do I search to find what SmartThings is doing to the oficial DTH's? I wouldn't believe my eyes if I saw that on their "docs" page

**Comment by ogiewon** [comment]
Look in their public github repo.

**Comment by vseven** [comment]
https://github.com/SmartThingsCommunity/SmartThingsPublic/tree/master/devicetypes/smartthings

**Comment by lestrauss** [comment]
Love you guys.

Should I close this issue or maybe leave it open 'til the new docs are ready, and maybe give a heads up here?

**Comment by ogiewon** [comment]
Closing for now.
