### ISSUE TITLE
Servo control "jitter" when idle.

### ISSUE THREAD

**Issue by gmerck** [DanielOgorchock/ST_Anything#159]
I have the servo control hooked up to the lever of a vent for open/close control over heating.  When in the fully closed position it is somewhat pushing against the lever to keep it closed, which seems to force the servo to constantly jitter.  Is there any way to put a timeout on the command so it will essentially power down the servo until the next command is recieved?

Oh, and also, how to reverse the servo controls, so 100 is 0, and 0 is 100?

**Comment by ogiewon** [comment]
At the top of every device class' files, you will find documentation on how to use the device.  For example, at the top of EX_Servo.h and .cpp, the following comment section outlines the parameters used to create the servo object in your sketch.  You can add the last two parameters to turn off power to the servo after a move has completed.

```

//******************************************************************************************
//  File: EX_Servo.h
//  Authors: Dan G Ogorchock
//
//  Summary:  EX_Servo is a class which implements the SmartThings/Hubitat "Switch Level" device capability.
//			  It inherits from the st::Executor class.
//
//			  Create an instance of this class in your sketch's global variable section
//			  For Example:  st::EX_Servo executor1(F("servo1"), PIN_SERVO, INITIAL_ANGLE, false, 1000);
//
//			  st::EX_Servo() constructor requires the following arguments
//				- String &name - REQUIRED - the name of the object - must match the Groovy ST_Anything DeviceType tile name
//				- byte pin_pwm - REQUIRED - the Arduino Pin to be used as a pwm output
//				- int startingAngle - OPTIONAL - the value desired for the initial angle of the servo motor (defaults to 90)
//              - bool detachAfterMove - OPTIONAL - determines if servo motor is powered down after move using following timeout (defaults to false) 
//              - int servoMoveTime - OPTIONAL - determines how long after the servo is moved that the servo is powered down if the above is true (defaults to 1000ms)
//
//  Change History:
//
//    Date        Who            What
//    ----        ---            ----
//    2018-06-23  Dan Ogorchock  Original Creation
//    2018-06-24  Dan Ogorchock  Since ESP32 does not support SERVO library, exclude all code to prevent compiler error
//    2018-08-19  Dan Ogorchock  Added feature to optionally allow servo to be powered down after a move
//
//
//******************************************************************************************

```

As for reversing the angles/dim levels...  You would probably need to modify the EX_Servo.cpp file, specifically the multiple lines that look like:

`m_nCurrentLevel = map(m_nCurrentAngle, 0, 180, 0, 99);`

to 

`m_nCurrentLevel = map(m_nCurrentAngle, 180, 0, 0, 99);`

**Comment by gmerck** [comment]
This is awesome - you truly have incorporated everything.

To confirm, the line in the sketch, around line 121 defining "servo_1", I should insert the "true" argument, like the following?

` static st::EX_Servo executor1(F("servo1"), PIN_SERVO_1, 90, true);  //last argument is the starting angle for the servo (0-180)`

**Comment by ogiewon** [comment]
You’ll need the ‘true’ plus one more argument after that for the amount of time before turning off the power to servo.  That last value does default to 1000ms if you exclude it.

**Comment by gmerck** [comment]
Perfect, thanks!  I got it working, but with some very strange delays.  After making the changes to this code I started to see long timeouts in the NodeMCU back on to wireless, and then registering with ST.  I'm not sure what kind of a fluke that was, but I also added a capacitor on to the input power (5v split to servo and Vin on NodeMCU via microUSB).  Since the last update, cramming it all in it's 3d printed box, *Oh, and changing it to type dimmer, I can now control the vent servo.

Last thing - to get Alexa/Google to do voice commands, I swapped the device type for the child to a dimmer.  Alexa didn't recognize it when it was a servo, but now I can say "Alexa, turn the vent all the way on" and it opens 100%.  "Alexa, turn off the vent" shuts it entirely - and the full range inbetween is available.

Thanks again for all the work on this!

**Comment by gmerck** [comment]
I think this is now 90% complete, but have one remaining issue.  I have implemented the device as a "child dimmer switch" to get it to be recognized by Alexa and Google Home, which works great, however turning it "on" does not resume the last dimmer percentage, and thus position, but "on" triggers the servo to move to 0 - the same place Off is.  Now that the servo is only on for 1 second, I hear it try, then power down the servo, but not change position.

What needs to be tweaked so an "on" state will resume the dimmer level, or is there a better way?

**Comment by ogiewon** [comment]
Take a look at this newer version of the servo driver I recently modified for Hubitat.  It allows preset values for both on and off. You may need to add a tile for the on/off switch capability. 

https://github.com/DanielOgorchock/ST_Anything/blob/master/HubDuino/Drivers/child-servo.groovy

**Comment by gmerck** [comment]
That did it.  Thanks a ton!
