### ISSUE TITLE
Architecture Flow Chart Image

### ISSUE THREAD

**Issue by jonathanweinberg** [DanielOgorchock/ST_Anything#16]
@DanielOgorchock - Can you upload/send me the original for the Architecture Flow Chart in the readme? I'd like to do some cleanup if you don't mind and send it back to you.

**Comment by ogiewon** [comment]
I have added the Architecture Flowchart power point slide to the repository, alongside the ReadMe.

**Comment by jonathanweinberg** [comment]
I appreciate it. I'll fork and return changes for you if you don't mind.

**Comment by ogiewon** [comment]
Always willing to accept offers for help!

**Comment by jonathanweinberg** [comment]
Working on it today! Do you mind a format change?

**Comment by ogiewon** [comment]
What do have in mind?  Just curious what you're proposing.  The Architecture slide was just a high-level overview so users could understand how the basic pieces of the architecture fit together.  

Are you proposing a much more detailed architectural diagram?  What format are you considering?

I am open-minded.  Just curious what you're thinking... :)

**Comment by jonathanweinberg** [comment]
Nothing that terrible :)

I re-made it in Draw.io and it needs a lot of work. Check what I did here: https://github.com/jonathanweinberg/ST_Anything/tree/master/RevisedFlow

**Comment by ogiewon** [comment]
It's been about 2 months since this "issue" was last updated.  I am closing it for now.  Please feel free to reopen it if you're still working on it.  One requirement, I would like to be able to maintain the flowchart with tools that I already have (i.e. PowerPoint) or something freely available and simple to use.

**Comment by jonathanweinberg** [comment]
Did you take a look at it?

**Comment by ogiewon** [comment]
Yes, I looked at it, but figured there must be more coming.  It basically looks the same as my PPT drawing.  I don't see a significant difference that warrants the change.  Perhaps you could explain the benefits?
