### ISSUE TITLE
Device Unable to create children

### ISSUE THREAD

**Issue by Tumtum2814** [DanielOgorchock/ST_Anything#165]
Using Arduino IDE 1.8.8 NodeMCU 12E Trying to implement the relay switch. It WAS working for a time and then stopped responding. 
I tried creating the device again, unsure if i had used 1.8,8 before and now it won't create a child device, i changed names and IP addresses after the few attempts with no success and that didn't do anything. 
Any ideas? The error i get is 
ST_Anything Parent Device has not yet been fully configured. Click the 'Gear' icon, enter data for all fields, and click 'Done'
But I've done that step a number of times.
--

**Comment by ogiewon** [comment]
I have tested Arduino IDE 1.8.8 with ESP8266 v2.4.2. Give that combination a try if you’re still having issues.

**Comment by LarryDysart** [comment]
I'm having a similar problem - Arduino 1.8.9 & ESP8266 v2.5.0. Turned on debugging on the ESP & it appears to get stuck waiting for responses in WiFi.Send somewhat randomly (sometimes initDevices has completed and sometimes not). Using the AlarmPanel_ESP8266WiFi example on a NodeMCU 12E. Don't think I've botched the library upgrades & left something old behind, but starting clean would be my next step if there are no other suggestions.

**Comment by ogiewon** [comment]
@LarryDysart - take a look at this user's post on the ST Community.  It may help you troubleshoot the issue.  
https://community.smartthings.com/t/release-st-anything-v2-9-2-arduino-esp8266-esp32-to-st-via-thingshield-ethernet-or-wifi/77707/2820?u=ogiewon

**Comment by LarryDysart** [comment]
Verified fixed using that change, thank you. Hub is using firmware version 000.025.00026 if that's helpful to the next person (although may not be relevant).

**Comment by ogiewon** [comment]
Thank you for the feedback!

**Comment by Tumtum2814** [comment]
I'm gonna try this this weekend and see what happens

**Comment by ogiewon** [comment]
The suggested change has been made to SmartThingsESP8266WiFi.cpp.  Thank you all for your feedback!
