### ISSUE TITLE
ESP8266 Can't add Device on another router on same network

### ISSUE THREAD

**Issue by raydiazz** [DanielOgorchock/ST_Anything#166]
My ST Hub is hardwired to the downstairs Wifi Router which is hardwired to my main router upstairs. The main Wifi router is upstairs. I can add the ST_Anything device to the downstairs router and all the child devices are created and everything works fine. I cannot add the ST_Anything device to the upstairs router that the ST Hub is not on. My upstairs router is 192.168.1.254. My downstairs Router is 10.0.01. My ST Hub is 10.0.0.2. Here is the two snippets of code for the different Routers I'm trying to add the device to.

String str_ssid     = "Upstairs";    
String str_password = "UpstairsPW";              
IPAddress ip(192, 168, 1, 237);     
IPAddress gateway(192, 168, 1, 254); 
IPAddress subnet(255, 255, 255, 0);   
IPAddress dnsserver(192, 168, 1, 254);  
const unsigned int serverPort = 8090; 

String str_ssid     = "Downstairs";                         
String str_password = "downstairsPW";            
IPAddress ip(10, 0, 0, 7);       
IPAddress gateway(10, 0, 0, 1);    
IPAddress subnet(255, 255, 255, 0);   
IPAddress dnsserver(10, 0, 0, 1);  
const unsigned int serverPort = 8090;

**Comment by DanielOgorchock** [comment]
Your two routers are each on different subnets. You either need to configure a routing rule on your upstairs router to route traffic destined for the 10.0.0.0/24 subnet to the downstairs router or configure one router to behave as an extender rather than an actual router.

**Comment by raydiazz** [comment]
I was afraid it was going to require more knowledge on my end. I will research that and see where I get. 

Thank you!!

**Comment by raydiazz** [comment]
Excellent advice. It's working great now. I turned on the extender function on my downstairs Netgear router and linked it to the upstairs Mac address and everything works as expected. Now the ST Hub is seen as being connected to the upstairs network even though it's plugged in to the downstairs router.

**Comment by ogiewon** [comment]
Glad to hear everything is working.  Closing this issue for now...
