### ISSUE TITLE
Device doesn't show up if OTA hostname contains underscore

### ISSUE THREAD

**Issue by fiz1962** [DanielOgorchock/ST_Anything#176]
In line 112 of SmartThingsESP8266WiFi.cpp, the Arduino OTA hostname is created and includes an underscore in the name

String("ESP8266_" + strMAC).toCharArray(st_devicename, sizeof(st_devicename));

Underscores are not allowed in hostnames and devices named as such do not show up as a Network Port for OTA programming in the Arduino IDE.  Changing this underscore to a dash allows the device to show up.  This is a known problem (see for example https://github.com/arduino/Arduino/issues/5240)

Proposed change to 
String("ESP8266-" + strMAC).toCharArray(st_devicename, sizeof(st_devicename));

From Wikipedia
The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9' and the hyphen-minus character ('-').

and

While a hostname may not contain other characters, such as the underscore character (_)

**Comment by ogiewon** [comment]
Thank you for your feedback.  I have included your suggested change to SmartThingsESP8266WiFi.cpp.
