### ISSUE TITLE
ArduinoOTA 1.0.1 locked up wifi on NodeMCU v3

### ISSUE THREAD

**Issue by cejennings** [DanielOgorchock/ST_Anything#178]
After much testing and debugging the SmartThingsESP8266WiFi library, i ended up commenting out the ArduinoOTA.handle(); line in the .cpp file.  While this was active, I had spotty to no working wifi.  After commenting this out - no wifi issues at all.

I had performed an update to my libraries using the Library Manager but didn't realize that this caused my issue until days later.  You might check to see if there is some incompatibility with this version of the ArduinoOTA library (1.0.1) and SmartThingsESP8266WiFi

**Comment by ogiewon** [comment]
What version of theRSP8266 board manager support are you using?

**Comment by ogiewon** [comment]
Are you using the Arduino OTA feature that is included with the ESP8266 Board Manager?  Or is this the newer ArduinoOTA that Arduino.cc has put out recently?  ST_Anything is designed to use the version that comes with the ESP8266 Board Manager package.  I haven't even looked at the Arduino.cc one yet.

**Comment by cejennings** [comment]
As I mentioned in my post, I had performed and update via the board manager. I will recopy the one included in your github site. By the way, do I actually lose functionality having OTA disabled?  (I’m a bit of a noob to this)

**Comment by ogiewon** [comment]
"As I mentioned in my post, I had performed and update via the board manager."  OK, but what did you update?  What it specifically ArduinoOTA?  If so, just remove that library altogether as the ESP8266 includes its own 'ArduinoOTA' support (there is no separate library for it, as it is part of the ESP8266 Board Manager Package instead.)  I believe you also need Python 2.7 installed on your computer for it to work.

**Comment by ogiewon** [comment]
Oh, and you really don't lose functionality without any ArduinoOTA support, other than having to use USB to reprogram your boards.

**Comment by ogiewon** [comment]
Any update?  If not, I’ll close this issue...

**Comment by cejennings** [comment]
Go ahead and close. I am out of country and have not been able to test. I will figure it out one way or the other. Thanks.
