### ISSUE TITLE
HX711 Support

### ISSUE THREAD

**Issue by adamwgray** [DanielOgorchock/ST_Anything#180]
I have a need to add support for HX711 sensors to take the weight of an object. Has this been worked on within this project? I am happy to help out. My struggle is more on the groovy side as I have not done any interface work within ST.

**Comment by ogiewon** [comment]
You are the first person to request a device that weighs an object. Are you aware of any SmartThings.Hubitat Standard Capabilities that can represent “weight”?

**Comment by adamwgray** [comment]
I don't think it is part of the standard capabilities within smartthings. There is a smart scale app for a specific scale in the smartthings public git repo.

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/smartapps/smartthings/withings.src/withings.groovy

Though the calls using the HX711 library and hardware are not that different than temp measurement. The two functions are tare the scale (one time or via a manual button) and read and report the scale over time. The scale reads in the HX711 library are float. Let me know what you think. 

This is one of the library options for the hardware.
https://github.com/bogde/HX711

**Comment by ogiewon** [comment]
Any progress on this?  I’d happily accept a PR for a new device class that supports the HX711.  For now, I am going to close this issue due to lack of activity. Please feel free to reopen it if there is any update.

**Comment by adamwgray** [comment]
I was waiting for feedback from you. I asked you some specific questions on
what would be needed to make it work within the project. I just assumed you
were too busy to get back to me.

Either way, if it is not a good fit then I will find another way to code up
what I need.

Let me know.

Adam

**Comment by ogiewon** [comment]
Adam,
You should be able to start with one of the existing temperature sensor device classes, and then create your own HX711 device class.  However, since ST does not have a standard capability that includes the ability to tare the scale, you’ll need to create a custom command, and build a custom scale child device handler, modify the parent DTH to be aware of the new child DTH, etc...

This is not something I have the time to pursue right now.

**Comment by adamwgray** [comment]
Thanks. I will take a look. I will come back when I get some time and get
close to a working model.

Adam

**Comment by blair287** [comment]
Get anywhere?

I would like to use a hx711 as a percentage so it knows 0kg is 0% and 1kg is 100% so Smartthings shows the percentage.
