### ISSUE TITLE
Thermostat capabilities

### ISSUE THREAD

**Issue by muxa** [DanielOgorchock/ST_Anything#185]
Do you have any plans to add support for Thermostat capabilities? 

I’m looking at making my Mitsubishi air conditioner smart with an ESP32 module and integrate it with Hubitat. 

I could help with the development. 

What would be a good path forward to achieve this?

**Comment by ogiewon** [comment]
I do not have any plans to create a thermostat device.  However, Hubitat already has a Virtual Thermostat device you could use, and then simply link that device to the HubDuino ESP32's temperature sensor and digital output to turn on/off the AC unit.
