### ISSUE TITLE
Restructure Directories to be "Arduino Library" Compliant

### ISSUE THREAD

**Issue by jnovack** [DanielOgorchock/ST_Anything#187]
Rather than the 7 step process to download and install the Arduino code which requires finding folders on hard-drives (yes, I've read the posts in the SmartThings community forum, this seems to be an unclimbable mountin for some), we can simplify process if you change the layout of the repo to be [arduino library](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) compliant.  This would require a user to only download the Zip File and click "Import Zip Library".  In fact, once we solidify the structure and test, [a few simple changes can put this in the official 'Manage Libraries...'](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) section.  It is one less barrier to entry towards adoption of this project.

This does come as a breaking repo change (which should [bump to v3](http://www.semver.org) at a minimum), but thankfully there is not that much documentation to change. ;)

This is quite a bit of restructuring and with a relatively stable code-base at this point, should be  a band-aid we rip off sooner rather than later.

This Arduino library specification MAY (we won't know without testing) conflict with keeping this also as a SmartThings IDE Github Repo.  It may be necessary (I am unsure at this time, but just pointing it out) to transport all the Arduino code out of this repo into a ST_Arduino (example name) library while this one remains the one for the SmartThings IDE.

My proposal is as follows:
* Create a new name for this project (this will be the hardest part!)
* Create an organization with three repositories (the arduino ide code, the smartthings ide code, documentation)

Or is this where OmniThing was headed?  I'm happy to jump on a Discord call to discuss this.

**Comment by ogiewon** [comment]
I really do appreciate the initiative.  However, I’d rather not totally restructure the repo at this point. Thank you for your understanding.
