### ISSUE TITLE
Rotary Dimmer Remote ESP8266

### ISSUE THREAD

**Issue by sciibus** [DanielOgorchock/ST_Anything#188]
Hi,
would it be possible to add a new "dimmer sensor" to the esp8266?
I was thinking in the sense of a Ky-040 rotary encoder hooked up to the esp8266 to be able to dim the lights or adjust fan speed or whatever. 
Sadly I don't know where to start implementing this.
Thanks!
Greetings

**Comment by ogiewon** [comment]
Hmmmm...  why not just use a few IS_Button devices.  These allow both Pushed and Held events.  You could use the pushed events for ON and OFF, and use the held events for increase and decrease.  

Are you using SmartThings?  Or Hubitat?

**Comment by sciibus** [comment]
I have solved it by extending the Ex_Switch_Dim class to enable inputs which I am driving with the KY-040. But thank you for your answer! Yea, the aurora looks good but the 40€ are a bit steep compared to the 5€ esp solution.

**Comment by ogiewon** [comment]
Great!  Glad to hear you found a solution.

**Comment by ryancasler** [comment]
I've been looking at trying to do the same thing.  Do you mind sharing your sketch and a quick description of how you have the encoder wired?  Thanks!

**Comment by ryderllama** [comment]
I too was curious if anyone had any specific examples on this that they had working? I'm pretty much trying to setup the exact same thing, but finding precious little on how to use rotary encoders (KY-040) as dimming devices outside of HomeAssistant MQTT, which I don't really want to do.  I'm new to coding with arduino IDE and the ESP8266, and thought this would be a cool way to learn more about it and extend my portfolio of Hubitat friendly devices.  I've got basic code working with ESPRotary() examples, outside of using ST_Anything, but not sure how to integrate that external library with the Ex_Switch_Dim class, and integrate it with ST_Anything  as the the author suggested was their solution . 

Any pointers would be appreciated.

**Comment by gregoughton** [comment]
> I have solved it by extending the Ex_Switch_Dim class to enable inputs which I am driving with the KY-040. But thank you for your answer! Yea, the aurora looks good but the 40€ are a bit steep compared to the 5€ esp solution.

 @samkenw Could you share some information on this project? I'm also looking to create a dimmer in ST_anything with a rotary encoder and would appreciate any info you could share!
