### ISSUE TITLE
Looking to add support for devices which use a serial to MCU setup for device control and monitoring.

### ISSUE THREAD

**Issue by slm4996** [DanielOgorchock/ST_Anything#190]
A good example of this device type is the LC Tech relay boards and quite a few Tuya devices.
The Tuya API is well documented here: https://docs.tuya.com/docDetail?code=K8uhkesnz5mie
and they even have demo code here: https://docs.tuya.com/docDetail?code=K8uhkdnjpaf5f

Basically the ESP device communicates over its serial pins to a MCU, which controls the relays or monitors sensors and reports back over serial to the ESP.

Listing of devices known to me to use this setup:
Relay https://www.aliexpress.com/item/32819462977.html
Inching relay and magnetic sensor https://www.aliexpress.com/item/4000121566970.html

Any ideas on how best to tackle this in a way that fits your design and logic flow for future inclusion into the project? I am focusing my effort first on a working implementation for the Garage Door Controller, as it is what I personally most need.

**Comment by IceBearZero** [comment]
@slm4996 Im working on this exact same thing, and started to peel the code apart to see where/how I can inject it... the learning curve feels a bit steep at the moment to find a good launch point.

Im actually using this: https://www.amazon.com/gp/product/B071WWMMDD/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1 .. and have gotten it to work with a simple sketch for triggereing the relay. Now triyng to get it ST_Anything connected ..

**Comment by slm4996** [comment]
I believe I may switch my work on this from ST_Anything to Omnithing. Still
evaluating the codebase to decide which way to go.

**Comment by IceBearZero** [comment]
I may wind up going with a piggy back virtual switch in ST, that Alexa watches and then uses FAUXESP to control .. lot less code

**Comment by slm4996** [comment]
Either way, the main problem is we are monitoring serial input and not a
pin. That sort of opposes the current framework.

I already have a standalone setup that works with SmartThings, I just want
to consolidate the firmware that I have to keep updated!

**Comment by IceBearZero** [comment]
The board I listed does that out of the gate .. 

```
#include <fauxmoESP.h>


#define LED 1
byte relON[] = {0xA0, 0x01, 0x01, 0xA2};  // Hex command to send to serial for open relay
byte relOFF[] = {0xA0, 0x01, 0x00, 0xA1}; // Hex command to send to serial for close relay

void setup()
{
 Serial.begin(9600);
}
void loop(){
  Serial.write(relON, sizeof(relON));
  delay(5000);
  
  Serial.write(relOFF, sizeof(relOFF));
  delay(5000);
}

```

**Comment by ogiewon** [comment]
If you want a very simple method of integrating the serial connected relay with SmartThings, you'll find it much simpler to to start with the old "SmartThings On/Off" example sketch.  This does not use ST_Anything, but uses the same SmartThings communications libraries.

https://github.com/DanielOgorchock/ST_Anything/blob/master/Arduino/libraries/SmartThings/examples/SmartThings_On_Off_LED_ESP8266WiFi/SmartThings_On_Off_LED_ESP8266WiFi.ino

Here is is the RaedMe

https://github.com/DanielOgorchock/ST_Anything/blob/master/Arduino/libraries/SmartThings/README.md

**Comment by slm4996** [comment]
Thanks @ogiewon , I have a functional sketch not using the SmartThings library, as I also needed to further customize the web services handling for other functionality. This will help merge that in.

@IceBearZero this is how to monitor incoming serial events, which may or may not help your scenario at all. https://www.arduino.cc/en/Tutorial/SerialEvent
Since your scenario only requires output and not input, just disable debug logging and edit line 49 of https://github.com/DanielOgorchock/ST_Anything/blob/master/Arduino/libraries/ST_Anything/IS_DoorControl.cpp to send the relevant serial on and off commands.

**Comment by IceBearZero** [comment]
Thanks!! Got something working with the on/off example. Everything is working **BUT** 
when I try to sent a `smartthing.send("off");` after I cause the relay to go back to off, the UI is never updated. 

Any thoughts on what may be keeping that sync from being updated on the UI side? @ogiewon

**Comment by ogiewon** [comment]
Are you using the ST Classic App?  Are you using the DTH that corresponds to the example On/Off sketch?  https://github.com/DanielOgorchock/ST_Anything/blob/master/Arduino/libraries/SmartThings/extras/On_Off_LED_Ethernet.device.groovy

If yes to both, have you tried manually refreshing the ST Classic App by dragging down on the screen and releasing?  The ST App sometimes gets stuck.  Always has.  But this does not affect automations that use the device.

Also, you should watch the ST Web IDE Live Logs to see if the data is coming back from the Arduino to the ST Cloud.

**Comment by IceBearZero** [comment]
@ogiewon .. Thanks so much for the guidance. 

- Using referenced DH - Yes
- Using Classic App - Yes
- Manually refreshing App - Yes, works about 1/3 of the time

Ive also watched the IDE logs. The 'sync' call is not often seen in there. I do have this strange issue where the MAC of the device as seen in my router is not the same as the MAC of the device (due to WIFI extender). I notice that in device setup you have fields for the MAC as well as the Device ID is supposed to be set to the MAC. I wonder if its getting confused with the MAC change - although Im not sure what you are using the MAC over the IP address for.

**Comment by ogiewon** [comment]
The MAC address is critical.  It must not change.  It is used by SmartThings to determine which ST device should receive the network packets from the Arduino board.

**Comment by IceBearZero** [comment]
It doesnt change, but there are 2 because of the extender. Things def. work better when I set it up with the virtual MAC given to the device via the router. But there is sometimes the sync confusion 

again -- thanks for the help

**Comment by ogiewon** [comment]
You’re welcome.
