### ISSUE TITLE
Child Devices Not Created Using Example Sketch

### ISSUE THREAD

**Issue by StaticVOiDance** [DanielOgorchock/ST_Anything#198]
### Development Platform
- Manjaro  Linux 5.5.16
- Arduino IDE 1.8.12

### Target Platform
- ESP-01
- ST_Anything Latest master 2.9.7

### Hub Platform
 - Nvidia Shield SmartThings Link
 - TV Client Version 1.1.1
 - Shield HubCore Version 0.20.12
 - Link FW 2.2.22

### Problem
Using stock example source code from ST_Anything_Multiples_ESP01WiFi. No child devices are created when updating the parent device settings in the ST app.

### Debugging Steps Taken
- Toggling number of buttons in ST app
- Tried Different Example Sketches
- Remove and re-adding Device Handlers from GitHub
- Remove and re-create parent device
- Verified ESP and ST Hub are reachable by their assigned static IPs
- Verified with NMAP that correct port on ESP are open

```
Nmap scan report for xxx.xxx.xxx.xxx
Host is up (0.0063s latency).
Not shown: 65534 closed ports
PORT     STATE SERVICE
8090/tcp open  opsmessaging
```

- Was not able to verify correct port open on ST Hub
```
Nmap scan report for xxx.xxx.xxx.xxx
Host is up (0.0081s latency).
Not shown: 65526 closed ports
PORT      STATE SERVICE
6466/tcp  open  unknown
6467/tcp  open  unknown
8008/tcp  open  http
8009/tcp  open  ajp13
8443/tcp  open  https-alt
8987/tcp  open  unknown
9000/tcp  open  cslistener
32400/tcp open  plex
38645/tcp open  unknown
```
### Logging Output
ST IDE
```
debug Using ip: [redacted] and port: 8090 for device: [redacted]
debug Executing 'sendEthernet' refresh
debug Executing 'updateDeviceNetworkID'
debug Hub Port = 0
debug Hub IP Address = 0.0.0.0
debug Executing 'updated()'
debug Executing 'updated()'
```
ESP Serial Monitor
```
Everything: init ended
Everything: Free RAM = 49592
Everything: adding sensor named motion1
Everything: Free RAM = 49592
Everything: adding sensor named contact1
Everything: Free RAM = 49592
Everything: initDevices started
Everything: Free RAM = 49592
IS_Motion: 30 second Motion Sensor Calibration Started...
Everything: Sending: contact1 open
Everything: initDevices ended
Everything: Free RAM = 49688
Everything: Received: refresh
Everything: Sending: motion1 inactive
Everything: Sending: contact1 open
IS_Motion: Motion Sensor Calibration Finished
Everything: Sending: motion1 i
```

I noticed that no port and address were listed in the ST IDE logs for the hub. I was thinking ST_Anything device handlers may not be compatible with NVIDIA Shield ST Link. Please confirm since it's not clear from the documentation.

**Comment by ogiewon** [comment]
I do not have any experience using an NVIDIA Shield as as ST hub.  Therefore, the issue could definitely be a result of that hardware combination. I know ST Hubs v1, v2, and v3 all work.

**Comment by StaticVOiDance** [comment]
How did you determine the 39500 port for the standard hub? I can also try again with some of the other open ports on my Shield. Do you know of a simple way to test to check if a port is the ST port? Like with Postman or something.

**Comment by ogiewon** [comment]
I discovered port 39500 was the correct one to use years ago by analyzing some example source code that other ST Community members had shared.

**Comment by ogiewon** [comment]
Here is one thread that confirms the existence of the problem that you are seeing...

https://community.smartthings.com/t/nvidia-shield-tv-smartthings-link-issues/131448?u=ogiewon

**Comment by StaticVOiDance** [comment]
I really appreciate the help. Once you mentioned this was likely an issue with my hub I stated to get somewhere. I found out there is a bug with the Hub Core for shield. It seems it when you change the IP address without a reboot it breaks the hub LAN functions. The solution was as simple as rebooting the hub.

**Comment by ogiewon** [comment]
Thank you for posting the solution.  This should help others in the future. Have fun!
