### ISSUE TITLE
Gate control signal?

### ISSUE THREAD

**Issue by bdice** [DanielOgorchock/ST_Anything#20]
I have been playing with the IS_DoorControl device. We have a gate that functions somewhat like a garage door, but its signal response seems to be different than your sample garage doors. The gate takes around 20 seconds to close. Here's the signal input we have:

- Open: 0V
- Closed: +5V
- Opening (going from closed to open): 0V
- Closing (going from open to closed): blinking in a square wave with period 1 second, between 0V and +5V for 20 seconds while the gate is moving

How would you recommend altering the code to make this have the correct status (open/closed/opening/closing) shown on SmartThings? I made a custom IS_GateControl device that currently works the same as the IS_DoorControl device, but I am not yet sure how I should alter it.

I have played with the math of using exponential moving averages and triggering a state change at some cutoff values, but that was in a Python script that simply checked to see if it would be possible. The event-driven nature of the ST_Anything code has made this a little more difficult since I don't have a timed loop.

If you have suggestions on how to implement an exponential moving average or triggering state changes manually, that would be helpful.

If I understood the signal input of the sample garage doors, that might also be helpful.

Thank you for your help!

**Comment by bdice** [comment]
The easiest possibility would be if the state-reading code was disabled for 20 seconds before reading again. While the gate is moving, if we just don't update the state on SmartThings, it will still say "opening" or "closing" until the motion is done, when the state can be read again to verify that it is "closed" or "open," respectively. (I don't know how to do this.)

**Comment by ogiewon** [comment]
So, I think you can accomplish everytrhing you want by simply modifying the the update() routine within your copy of the IS_DoorControl class.  If you look through this, you'll see that the function is called every time through the Arduino sketch's loop() routine.  So it provides you an opportunity to do whatever you'd like.  In the case of the standard IS_DoorControl below, I evaluate whether or not is is time to turn off the digital output based on the duration passed into the constructor.  In your case, you could modify this to determine if you are "opening the gate" to generate the square wave needed to close the gate.  You could also skip the very last line which calls the IS_DoorControl's C++ parent class, InterruptSensor, to perform a normal check of the contact sensor input.  

Obviously, there would need to be some special logic changes to make sure the digital ouput is left in the correct state depending on whether you are opening or closing the gate.  The standard IS_DoorControl always turns off the output as it is designed to interafce with a garage door opener wall-mounted button.

	void IS_DoorControl::update()
	{
		//Turn off digital output if timer has expired
		if ((m_bCurrentState == HIGH) && (millis() - m_lTimeTurnedOn >= m_lDelayTime))
		{	
			m_bCurrentState = LOW;
			writeStateToPin();
			//Decrement number of active timers
			if (st::Everything::bTimersPending > 0) st::Everything::bTimersPending--;
			m_bTimerPending = false;
		}

		//check to see if input pin has changed state
		InterruptSensor::update();
	}

Hopefully this gets you started!
