### ISSUE TITLE
Latest Hubitat Firmware Broke Mapping to MAC Address

### ISSUE THREAD

**Issue by ryancasler** [DanielOgorchock/ST_Anything#201]
Don't know if you experienced this but I have a bunch of boards on older drivers that still uses the MAC address entered manually to map to the DNI.  After updating to 2.2.0.130 today, it was unable to match a device to parse any of those messages so all of the board stopped working.  Kept getting the "cannot find a device to match" messages.  Don't know if this is related to the mysterious "security update" listed in the release notes or what.  But just thought I would let you know.  I'm going to go through and update all my DNI's for my child devices manually so I don't have to recreate them all, so then it won't matter.

**Comment by ogiewon** [comment]
Thanks Ryan.

**Comment by ryancasler** [comment]
Actually not sure that was the problem after all...although, now I don't know what might have caused it.  It just completely stopped matching up to the appropriate device.  Had to go through and modify the DNI's manually.  But they're all still working, thank goodness.
