### ISSUE TITLE
0-1023 PWM mapping for ESP8266 missing in EX_RGBW_Dim.cpp

### ISSUE THREAD

**Issue by moosty-moo** [DanielOgorchock/ST_Anything#202]
Hi,

I see that PWM mapping was added in EX_Switch_Dim.cpp &  EX_RGB_Dim.cpp to handle the 0-1023 range for the ESP8266.
Could the change be made in EX_RGBW_Dim.cpp also?

**Comment by ogiewon** [comment]
Happy to accept a pull request with this enhancement. I have no good way to test the change, so any help would be appreciated. The EX_RGB and EX_RGBW devices were actually community created.

**Comment by ogiewon** [comment]
@moosty-moo - I have taken a stab at making the changes you requested to EX_RGBW_Dim.cpp.  Please give it a try and let me know if it works.  I have not tested these changes whatsoever, so I am counting on your feedback.  Thanks!

**Comment by moosty-moo** [comment]
Thank you - I’ll test that now. 
Sorry for the late reply - it was midnight here in the UK and I’d gone to bed.

Regards, Chris. 

On 10 Jun 2020, at 03:46, ogiewon <notifications@github.com> wrote:

﻿


@moosty-moo - I have taken a stab at making the changes you requested to EX_RGBW_Dim.cpp. Please give it a try and let me know if it works. I have not tested these changes whatsoever, so I am counting on your feedback. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/DanielOgorchock/ST_Anything/issues/202#issuecomment-641686599", "url": "https://github.com/DanielOgorchock/ST_Anything/issues/202#issuecomment-641686599", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by moosty-moo** [comment]
Hi,



That's working fine. You are the Big Cheese.

Many hanks for that. 

I can confirm that all 4 channels ( red,green,blue,white) are now running at full power when set to 100%.



Regards, Chris.





-----Original message-----

**Comment by ogiewon** [comment]
Awesome!  Thanks for the feedback.
