### ISSUE TITLE
ST_Anything stopped working after switching to new mobile app

### ISSUE THREAD

**Issue by rlatreille** [DanielOgorchock/ST_Anything#214]
My ST_Anything buttons and switches stopped working after trying out the new  SmartThing mobile app.
Is there a fix for that?

**Comment by ogiewon** [comment]
FYI - My house is 100% running on Hubitat for the past 2.5 years. As such, I will not be putting much, if any, effort to the SmartThings platform these days. Especially knowing that ST intends to shut down the Legacy Groovy IDE altogether in 2021.  

If others figure out how to make the ST_Anything Device Type Handlers work better with the New ST App, I am happy to accept Pull Requests to this repository.

**Comment by rlatreille** [comment]
Thanks Daniel,
My Habitat hub is on its way

Robert

On Aug 16, 2020, at 08:35, ogiewon <notifications@github.com> wrote:

﻿
FYI - My house is 100% running on Hubitat for the past 2.5 years. As such, I will not be putting much, if any, effort to the SmartThings platform these days. Especially knowing that ST intends to shut down the Legacy Groovy IDE altogether in 2021.

If others figure out how to make the ST_Anything Device Type Handlers work better with the New ST App, I am happy to accept Pull Requests to this repository.

**Comment by vseven** [comment]
I don't have any buttons or switches but if the changes are like the ones I did to temperature and humidity it should be pretty quick fix. I'll take a look at it later this week.

**Comment by ogiewon** [comment]
I made a few minor tweaks this week to add some units to a few child device handlers.  Also removed some redundant/deprecated capabilities from a few child DTH’s to help make them work better in the New App.  BTW, that app does not perform well at all. 😜

**Comment by kkalbaugh** [comment]
@rlatreille  I don't know if it helps, but I noticed if I deleted the children and the parent and re-setup everything it works as long as I don't rename anything.  As soon as I rename any of the children it breaks.

**Comment by ogiewon** [comment]
> As soon as I rename any of the children it breaks.

Just curious if you're using iOS or Android to run the new ST Mobile App on?  Also, what happens if you rename (i.e. change the Label) via the Web-based IDE instead of using the phone app?

**Comment by kkalbaugh** [comment]
@ogiewon I'm using the new ST Mobile App on iOS.   I tried renaming on the web and it seemed to work.  What I noticed is that when I rename in the app it changes the device type to "placeholder" instead of "Child Relay Switch", "Child Switch", etc.

**Comment by ogiewon** [comment]
Isn't that New ST App just the best? ;)

**Comment by ogiewon** [comment]
I have updated all of the SmartThings DTHs to hopefully improve compatibility with the 'New' ST Mobile App.  Therefore, I am closing this issue.
