### ISSUE TITLE
ENC28J60

### ISSUE THREAD

**Issue by jrich523** [DanielOgorchock/ST_Anything#22]
Sorry wasnt really sure where else to ask, but is this ethernet interface supported? I tried to see if the ESP8266 would cover it but i came back with mixed answers.

if it is not supported what would it take to add support?

Thanks!

**Comment by ogiewon** [comment]
The ENC28J60 is not currently supported.  May I ask why this Ethernet interface is more attractive than the W5100 or W5500 Ethernet Shields?  I have seen it while searching for similar topics on the web, but never saw a reason to pursue it.  The information in this link makes me reluctanto support it:

https://forum.arduino.cc/index.php?topic=115464.15

The ESP8266WiFi support is for running everything on an ESP8266 based board.

**Comment by jrich523** [comment]
It just happens to be what I have. Was trying to avoid purchasing a new shield if i could get this to work, but this link plus a few others I have stumbled across makes me think i should just scrap it.

thanks for the response!
