### ISSUE TITLE
NeoPixelBus library needs added and some other issues/comments

### ISSUE THREAD

**Issue by vseven** [DanielOgorchock/ST_Anything#220]
The programmable RGB control is all based on NeoPixelBus because as previously mentioned NeoPixel is buggy and uses a older bit banging technology that suffers timing issues on a ESP8266 and simply doesn't work almost at all on a ESP32.  With that said to stick with how ST_Anything does something I'd ask that the NeoPixelBus library be added (https://github.com/Makuna/NeoPixelBus) and the NeoPixel library be removed as to not conflict with it.

Now the one issue with the NeoPixelBus addition is when the object is created it requires a [feature](https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#neo-features) and [method ](https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#neo-methods) declaration.  The feature is the order of the LED's so by default its "NeoGrbFeature" which is the most common.  The method is how the pixels are updated which by default is "Neo800KbpsMethod" which works for most strips but there are platform specific ones and ones for other programmable Led types.

So the question for @ogiewon is how does one pass these two things in from the sketch?  I'm not a C# programmer (vb.net is my main) but do you have to declare the NeoPixelBus.h in the sketch and then use those or can you pass them as strings?  I'm trying to make the .h and .ccp never have to be touched and that's the last step.  Conceivably then you could have different types of programmable strips and use a single ESP32 to control them.  I attempted to add the two as strings and pass them in through the sketch but could not get it working correctly and I'm assuming you've seen this and have a quick fix.  I can make the changes with a little guidance.

Side note - I just picked up a 5 meter 150 led strip this weekend and this library worked perfect for it.  But I'd like to figure out the above so I can test using two different strips.  I have one that's Brg ordered (1m, 60 LEDs) and one that's Grb ordered (5m, 150 LEDs).

**Comment by ogiewon** [comment]
@vseven I have added the NeoPixelBus_by_Makuna to the ST_Anything GitHub repository per your request.  I have left the Adafruit_NeoPixel library in place, as its files are all uniquely named compared to the NeoPixelBus_by_Makuna library.  There should not be any conflicts when building code.  Please let me know if you find this not to be the case.

**Comment by vseven** [comment]
Thanks!  Any hints on passing the method or feature in from the sketch?  I tried to find a example in other libraries and didn't get very far.

**Comment by ogiewon** [comment]
Since your EX_RGB_NeoPixelBus.h header file will be included in the sketch, and since it already includes NeoPixelBus.h, there is no need to directly include NeoPixelBus.h in the sketch.  You should be able to create objects from the NeoPixelBus library and pass them into the constructor of the EX_RGB_NeoPixelBus device.

One thing I just realized is that you added EX_RGB_NeoPixelBus.h and .cpp in the main ST_Anything library.  For devices like this, that depend so heavily on another third=party library, I typically keep those in a separate library folder.  I will move EX_RGB_NeoPixelBus.h and EX_RGB_NeoPixelBus.cpp into their own ST_Anything_NeoPixelBus library.  This will not affect any code in the sketch.  It is just my system for keeping the code organized that has external library dependencies.

**Comment by ogiewon** [comment]
I have finished moving both of the NeoPixel-based libraries into their own ST_Anything library folders.

**Comment by ogiewon** [comment]
I have also just moved the RGBW library files into ST_Anything_NeoPixelBus  along with their RGB cousins.

**Comment by vseven** [comment]
May also want to move the standard NeoPixel one the other guy wrote to it's own directory for the same reason.  I have a NeoPixel library also if you want it that does support passing in pixel count and pin correctly with a example sketch.  But as I said before you'd be better of to remove it as it doesn't work with more then a couple LED's due to how that library works.  Both NeoPixelBus and FastLED are massive improvements, NeoPixelBus just happened to be easier to implement.


As for passing in the feature and method to the call in the sketch maybe my inexperience of how C# works or there is a limitation on how the NeoPixelBux object is created.  For example I tried passing it in like this:

`static st::EX_RGB_NeoPixelBus         executor1(F("rgbSwitch1"), 60, PIN_RGB1, NeoGrbFeature, Neo800KbpsMethod ); `

What you said was correct, since the EX_RGB_NeoPixelBus.h calls NeoPixelBus.h the feature and method show up in red so it knows what they are so that's good.  I then tried updating the constructor in the EX_RGB_NeoPixelBus.h file public constructor:

EX_RGB_NeoPixelBus(const __FlashStringHelper *name, uint16_t pixelCount, uint8_t pinRGB, T_COLOR_FEATURE myFeature, T_METHOD myMethod);

Then when creating the strip using this:

NeoPixelBus<myFeature, myMethod> m_nStrip;

But this fails with a "error: 'myFeature' was not declared in this scope".  Maybe I don't understand the order things are being processed in but I don't seem to be able to send over the feature and method to the strip object decoration.  There was someone else trying to get ST_Anything and NeoPixelBus working together almost three years ago (https://gitter.im/Makuna/NeoPixelBus?at=5971882c76a757f8083008a1) and it looks like they were having the same issue I'm having.  The author of NeoPixelStrips responded with a Wiki titled "How do I store a reference to the NeoPixelBus in another class" https://github.com/Makuna/NeoPixelBus/wiki/FAQ-%2311 but it doesn't make much sense to me.

**Comment by ogiewon** [comment]
I already moved the other Adafruit NeoPixel-based code into its own folder as well. I am hesitant to remove it at this time, even with its known issues. 

As for the issue with passing in the configuration data into the constructor, i would have to spend time in the Arduino IDE to debug the issue. I don’t have a ton of time right now to do that.

**Comment by vseven** [comment]
I'm gonna play with it for a bit and see what I can come up with.  I think I understand the WiKi article....just havet o figure out how to apply to ST_Anything.  Would be good if I can, programmable LED's are a lot easier to wire up then analog and the ability to support multiple different types from one ESP32 would be cool.  The hardware will allow 8 RMT outputs at a time so you could do some neat things with a big strip cut down into sections.

**Comment by vseven** [comment]
So got this working with a templated library.  It's actually kinda slick....can do up to 8 LED strips from a single ESP32 since it supports up to 8 RMT channels.  Weird issue I'm running into and I don't know if this is the addition of the NeoPixelBus library or a flaky ESP32.  Sometimes I see the refresh run on the controller (in serial monitor) and I'll get a host timed out.  I'm assuming that's the ESP32 trying to talk to the hub and not getting a reply?   Also sometimes I send a command from the app (classic or new, doesn't matter) and the arduino never gets the command.  Doesn't matter if its a on/off or color command.

I haven't fully tracked it down but wanted to know if you've ever seen that before.

**Comment by ogiewon** [comment]
I have seen some strange things over the years between SmartThings and the Arduino boards.  But, it's usually resolved with a hard reboot of the ST hub or a reboot of the Arduino.  Sounds like your issue is more intermittent, though.  Not sure about that...

**Comment by vseven** [comment]
Yeah, I can't really see it being the code since it's only being called when a command is set.  And the periodic refreshes are even timing out occasionally.  I haven't rebooted my hub in a long time, I'll start there.  If that fixes it I'll push the new library with multi strip support.

**Comment by vseven** [comment]
FYI - I flashed my ESP32 to the latest factory firmware image, reloaded my sketch, and no issues.  Might have been something in the firmware, might have been the ST cloud being goofy.  Either way the library seems stable.  Just pushed my new files and I'll close this.

Side note:  The NeoPixelBus library was recently updated to v2.6.0 and had a couple minor updates that seems to help with running multiple strips so if you get a chance please grab the latest version.
