### ISSUE TITLE
Direct calls to ST_Anything device

### ISSUE THREAD

**Issue by gadget-man** [DanielOgorchock/ST_Anything#227]
Question rather than an issue: I'm running ST_Anthing on an Android device and it works fine with the (Old) SmartThings app. However is it also possible to make direct calls to the device to send actions knowing only the IP address? - I've got a separate ESP32 running and would like to be able to either send a command over ST, or from the other ESP32.

**Comment by ogiewon** [comment]
It is technically possible, I believe.  You'd have to reverse engineer the packet format by looking at the existing Parent Groovy code that sends data to the microcontroller and emulate that same behavior on your ESP32.  You have to use both the IP address and Port (e.g. 8090) that the ST_Anything library listens on.  

Note, this is not a supported method, so you're on your own to make it happen.
