### ISSUE TITLE
More button and none switch 

### ISSUE THREAD

**Issue by dudl00** [DanielOgorchock/ST_Anything#228]
Hello i new on this :) 
i have hubitate hub and i like to use ESP8226  for 7 physical/buttons/debunce.

I tested script  ST_Anything_Relays_Butttons_ESP8266.ino   work great.  Script have 3 button and 3 relays. i fail to do just buttons :(
If i make 7 buttons  child device not created :(  if some use or have worked script or it helps me to repair i be very grateful :) 
 
Thanks and goodbye
Klemen

**Comment by ogiewon** [comment]
Correct.  There are no child devices for IS_Button devices.  The Parent Device is the “Button Controller”, which will produce “pushed”, “held”, and released” events which can be used in various Apps, such as Button Controllers, ABC, and Rule Machine.

Note: the “buttons” in the ST_Anything_Relays_Buttons... sketch are local only to the microcontroller.  Those buttons are not shared with the Hubitat Hub as they only toggle the local EX_Switch devices in the sketch.

**Comment by dudl00** [comment]
Hello, thanks for quick response. 
For my  smart home project i need 7 button on wall and if i use ESP8266 with relay output i don`t have enough inputs :(
For Hubitat hub/Rule Machine i need just inputs. And on other location in electric cabinet i will need just outputs with relays.

Can i somehow create child device but with (no outputs/no inputs) on ESP8266🥇 or do i need other device and cable to electric cabinet?

**Comment by ogiewon** [comment]
@dudl00 - I am having a hard time understanding what your requirements are exactly.  Please explain exactly what you are trying to accomplish.  

I will try to answer your question based on my best guess of what you're asking.  It sounds like you simply want to use an ESP8266 with 7 buttons connected to it?  Is that correct?  And then have those buttons generate 'pushed', 'held', and 'released' events to your Hubitat hub, so Apps like 'Simple Automations', 'Button Controllers', or 'Rule Machine' can execute logic.  Is this correct?  

If so, then simply use the following sketch as a starting point...  

https://github.com/DanielOgorchock/ST_Anything/blob/master/Arduino/Sketches/ST_Anything_Buttons_ESP8266WiFi/ST_Anything_Buttons_ESP8266WiFi.ino

I simply modified the ST_Anything_Multiples_ESP8266.ino sketch as I mentioned above, to have seven IS_Button devices defined, which use pins D1-D7 on the NodeMCU ESP8266 board.  NOTE: Make sure these buttons are not pushed which the ESP8266 board is booting up, as it can have very undesirable results, especially for pins D3 and D4.

I have tested it using my Hubitat hub and it works exactly as expected.

**Comment by dudl00** [comment]
Works wonderfully. Thank you very much mate!
Sorry for the late reply, I'm renovating the house :)
If I have any more problems I hope I can point it out? 

Have a nice day

**Comment by ogiewon** [comment]
Glad to hear it is working.  For the best support, please post in the SmartThings Community forum under the ST_Anything thread, or the Hubitat Community forum under the HubDuino thread.
