### ISSUE TITLE
No "import from Git" in SmartThings IDE

### ISSUE THREAD

**Issue by SunboX** [DanielOgorchock/ST_Anything#236]
Hi,

first, let me thank you for you great work!

I did not find any way to import all the scripts from Git automatically. So I added all by hand.

**Comment by ogiewon** [comment]
What country are you in?  Samsung restricts GitHub integration to a limited number of countries. There is nothing I can do about that.

**Comment by SunboX** [comment]
Oh, that's sad. I'm from Germany. Maybe I can switch my account to US.

**Comment by SunboX** [comment]
Can you leave a warning in the Readme for this? Would be helpful for others that come acros this issue. :)

**Comment by ogiewon** [comment]
Sure.  I have added the following to the top of the ReadMe.

WARNING - SmartThings Web IDE GitHub integration is not available in all countries around the globe.
