### ISSUE TITLE
Unable to add all device handlers via Github repo update

### ISSUE THREAD

**Issue by CubanJew** [DanielOgorchock/ST_Anything#242]
Trying to re-install ST_Anything via SmartThings IDE and unable to add all of the Device Handlers via Github repo update.

Unable to execute update for:

>  devicetypes/ogiewon/child-ultrasonic-sensor.src/st-device-config.json
>  devicetypes/ogiewon/parent-st-anything-ethernet.src/st-device-config.json
>  devicetypes/ogiewon/st-capabilities/README.md
>  devicetypes/ogiewon/st-capabilities/last-updated/st-capability.json
>  devicetypes/ogiewon/st-capabilities/last-updated/st-presentation.json
>  devicetypes/ogiewon/st-capabilities/refresh/st-capability.json
>  devicetypes/ogiewon/st-capabilities/refresh/st-presentation.json
>  devicetypes/ogiewon/st-capabilities/ultrasonic/st-capability.json
>  devicetypes/ogiewon/st-capabilities/ultrasonic/st-presentation.json
> 

This is the error I get:
> Oh No! Something Went Wrong!
> Error 500: Internal Server Error
> URI: /ide/device/doRepoUpdates
> Reference Id:  074d9559-14b3-4fc6-9bd3-eb092cc8229c

 I have tried restarting SmartThings Hub, and checking/unchecking "publish" option during update via Github.

I'm not sure how to add these manually.

**Comment by ogiewon** [comment]
Ignore those json files.  They’re not need for the import into the ST IDE.  They were recently added by another user to support the New ST App better.
