### ISSUE TITLE
Seems Compiler won't compile IS_Contact.cpp

### ISSUE THREAD

**Issue by mikelupo** [DanielOgorchock/ST_Anything#243]
Trying to recompile my Furnace Alarm code (it's been a few years!)
I can't seem to get the sketch to compile due to the errors seen below.
Any help will be appreciated.

Arduino: 1.8.13 (Mac OS X), Board: "Arduino Uno"

ST_Anything_FurnaceAlarm:84:64: error: no matching function for call to 'st::IS_Contact::IS_Contact(const char [8], int, int, bool, int)'
 st::IS_Contact sensor1("contact", PIN_CONTACT, LOW, true, 20000);
                                                                ^
In file included from /Users/mlupo/Documents/Arduino/Sketches/ST_Anything_FurnaceAlarm/ST_Anything_FurnaceAlarm.ino:57:0:
/Users/mlupo/Documents/Arduino/libraries/ST_Anything/IS_Contact.h:43:4: note: candidate: st::IS_Contact::IS_Contact(const __FlashStringHelper*, byte, bool, bool, long int)
    IS_Contact(const __FlashStringHelper *name, byte pin, bool iState, bool internalPullup = false, long numReqCounts = 0); //(defaults to NOT using internal pullup resistors, and required counts = 0)
    ^~~~~~~~~~
/Users/mlupo/Documents/Arduino/libraries/ST_Anything/IS_Contact.h:43:4: note:   no known conversion for argument 1 from 'const char [8]' to 'const __FlashStringHelper*'
/Users/mlupo/Documents/Arduino/libraries/ST_Anything/IS_Contact.h:36:8: note: candidate: constexpr st::IS_Contact::IS_Contact(const st::IS_Contact&)
  class IS_Contact: public InterruptSensor
        ^~~~~~~~~~
/Users/mlupo/Documents/Arduino/libraries/ST_Anything/IS_Contact.h:36:8: note:   candidate expects 1 argument, 5 provided
/Users/mlupo/Documents/Arduino/Sketches/ST_Anything_FurnaceAlarm/ST_Anything_FurnaceAlarm.ino: In function 'void loop()':
ST_Anything_FurnaceAlarm:147:23: error: 'setLED' is not a member of 'st::Everything'
       st::Everything::setLED(2,0,0);
                       ^~~~~~
ST_Anything_FurnaceAlarm:154:23: error: 'setLED' is not a member of 'st::Everything'
       st::Everything::setLED(0,2,0);
                       ^~~~~~
exit status 1
no matching function for call to 'st::IS_Contact::IS_Contact(const char [8], int, int, bool, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ogiewon** [comment]
Try changing

st::IS_Contact sensor1("contact", PIN_CONTACT, LOW, true, 20000);

to

st::IS_Contact sensor1(F("contact1"), PIN_CONTACT, LOW, true, 20000);

**Comment by mikelupo** [comment]
Still error in compilation.
In regards to your comment about the F String, PIN_CONTACT = 11. Should then, the F String, be "contact11" ?
setLED isn't happy. It's commented out in master.  I'll go back to an earlier tag and see if I can reimplement just that block of code....
Be advised...I am still using a ThingShield.  That's likely going to mean bringing in some older code. Perhaps starting with an older tag instead of Master? But will it work with the newer Arduino.h file from the newer IDE....

------ from the compilation log --------

In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:28:0,
                 from sketch/ST_Anything_FurnaceAlarm.ino.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.h:38:74: error: statement-expressions are not allowed outside functions nor in template-argument lists
 #define F(string_literal) (reinterpret_cast<const __FlashStringHelper *>(PSTR(string_literal)))
                                                                          ^
/Users/mlupo/Documents/Arduino/Sketches/ST_Anything_FurnaceAlarm/ST_Anything_FurnaceAlarm.ino:85:24: note: in expansion of macro 'F'
 st::IS_Contact sensor1(F("contact1"), PIN_CONTACT, LOW, true, 20000);
                        ^
/Users/mlupo/Documents/Arduino/Sketches/ST_Anything_FurnaceAlarm/ST_Anything_FurnaceAlarm.ino: In function 'void loop()':
ST_Anything_FurnaceAlarm:148:23: error: 'setLED' is not a member of 'st::Everything'
       st::Everything::setLED(2,0,0);
                       ^~~~~~
ST_Anything_FurnaceAlarm:155:23: error: 'setLED' is not a member of 'st::Everything'
       st::Everything::setLED(0,2,0);
                       ^~~~~~
exit status 1
'setLED' is not a member of 'st::Everything'

**Comment by ogiewon** [comment]
Let’s start from the beginning.  What are you trying to accomplish?  Please simply start with one of the example sketches in the GitHub repo.  Until you get one of those working, there is no need to write your own sketch. 

Are you using an old ST ThingShield?  If not, the setLED function does not exist.

**Comment by ogiewon** [comment]
I just reread your first post, where you mention trying to recompile an old sketch.  Lots of things have changed over the years.  Perhaps if you would post your sketch here, I could take a look at it and see what may need to be changed.

**Comment by ogiewon** [comment]
@mikelupo  - Did I help you with this sketch, many years ago?  I found a sketch in my sketches folder with the same name as yours.  It is definitely an old sketch, and required some significant updates.  Here is what I came up with, and it compiles!  I have not tested it on an actual Arduino + ThingShield combination.  Please give it a try and let me know if it works for you.

```
//******************************************************************************************
//  File: ST_Anything_FurnaceAlarm_New.ino
//  Authors: Dan G Ogorchock & Daniel J Ogorchock (Father and Son)
//
//  Summary:  This Arduino Sketch, along with the ST_Anything library and the revised SmartThings 
//            library, demonstrates the ability of one Arduino + SmartThings Shield to 
//            implement a multi input/output custom device for integration into SmartThings.
//            The ST_Anything library takes care of all of the work to schedule device updates
//            as well as all communications with the SmartThings Shield.
//
//            During the development of this re-usable library, it became apparent that the 
//            Arduino UNO R3's very limited 2K of SRAM was very limiting in the number of 
//            devices that could be implemented simultaneously.  A tremendous amount of effort
//            has gone into reducing the SRAM usage, including siginificant improvements to
//            the SmartThings Arduino library.  The SmartThings library was also modified to
//            include support for using Hardware Serial port(s) on the UNO, MEGA, and Leonardo.
//            During testing, it was determined that the Hardware Serial ports provide much
//            better performance and reliability versus the SoftwareSerial library.  Also, the
//            MEGA 2560's 8K of SRAM is well worth the few extra dollars to save your sanity
//            versus always running out of SRAM on the UNO R3.  The MEGA 2560 also has 4 Hardware
//            serial ports (i.e. UARTS) which makes it very easy to use Hardware Serial instead 
//            of SoftwareSerial, while still being able to see debug data on the USB serial 
//            console port (pins 0 & 1).  
//
//            Note: We did not have a Leonardo for testing, but did fully test on UNO R3 and 
//            MEGA 2560 using both SoftwareSerial and Hardware Serial communications to the 
//            Thing Shield.
//    
//  Change History:
//
//    Date        Who            What
//    ----        ---            ----
//    2015-01-03  Dan & Daniel   Original Creation
//    2015-03-10  Dan            Modified to monitor furnace alarm
//    2015-03-14  Dan            Added LED capability for visual status of the FurnaceAlarm
//    2015-03-31  Daniel O.      Memory optimizations utilizing progmem
//
//******************************************************************************************

//******************************************************************************************
// SmartThings Library for Arduino Shield
//******************************************************************************************
//#include <SoftwareSerial.h> //Arduino UNO/Leonardo uses SoftwareSerial for the SmartThings Library
#include <SmartThingsThingShield.h>    //Library to provide API to the SmartThings Shield
//#include <avr/pgmspace.h>

//******************************************************************************************
// ST_Anything Library 
//******************************************************************************************
#include <Constants.h>       //Constants.h is designed to be modified by the end user to adjust behavior of the ST_Anything library
#include <Device.h>          //Generic Device Class, inherited by Sensor and Executor classes
#include <Sensor.h>          //Generic Sensor Class, typically provides data to ST Cloud (e.g. Temperature, Motion, etc...)
#include <Executor.h>        //Generic Executor Class, typically receives data from ST Cloud (e.g. Switch)
#include <InterruptSensor.h> //Generic Interrupt "Sensor" Class, waits for change of state on digital input 
#include <PollingSensor.h>   //Generic Polling "Sensor" Class, polls Arduino pins periodically
#include <Everything.h>      //Master Brain of ST_Anything library that ties everything together and performs ST Shield communications

#include <IS_Contact.h>      //Implements an Interrupt Sensor (IS) to monitor the status of a digital input pin

//******************************************************************************************
//Define which Arduino Pins will be used for each device
//  Notes: -Serial Communications Pins are defined in Constants.h (avoid pins 0,1,2,3
//          for inputs and output devices below as they may be used for communications)
//         -Always avoid Pin 6 as it is reserved by the SmartThings Shield
//
//******************************************************************************************
//"RESERVED" pins for SmartThings ThingShield - best to avoid
#define PIN_O_RESERVED               0  //reserved by ThingShield for Serial communications OR USB Serial Monitor
#define PIN_1_RESERVED               1  //reserved by ThingShield for Serial communications OR USB Serial Monitor
#define PIN_2_RESERVED               2  //reserved by ThingShield for Serial communications
#define PIN_3_RESERVED               3  //reserved by ThingShield for Serial communications
#define PIN_6_RESERVED               6  //reserved by ThingShield (possible future use?)

#define PIN_CONTACT              11

//If using SoftwareSerial (e.g. Arduino UNO), must define pins for transmit and receive
#define pinRX 3
#define pinTX 2

//Global Variables
bool lastStatus;  //Hold the last status of the Furnace Alarm to prevent updating the LED too frequently
st::IS_Contact *sensor1p; //pointer for use in main loop

//******************************************************************************************
//Arduino Setup() routine
//******************************************************************************************
void setup()
{
  //******************************************************************************************
  //Declare each Device that is attached to the Arduino
  //  Notes: - For each device, there is typically a corresponding "tile" defined in your 
  //           SmartThings DeviceType Groovy code
  //         - For details on each device's constructor arguments below, please refer to the 
  //           corresponding header (.h) and program (.cpp) files.
  //         - The name assigned to each device (1st argument below) must match the Groovy
  //           DeviceType Tile name.  (Note: "temphumid" below is the exception to this rule
  //           as the DHT sensors produce both "temperature" and "humidity".  Data from that
  //           particular sensor is sent to the ST Shield in two separate updates, one for 
  //           "temperature" and one for "humidity")
  //******************************************************************************************
  //Polling Sensors
  
  //Interrupt Sensors 
  static st::IS_Contact sensor1(F("contact1"), PIN_CONTACT, LOW, true, 20000);
  sensor1p=&sensor1;
  
  //Executors


  //*****************************************************************************
  //  Configure debug print output from each main class 
  //  -Note: Set these to "false" if using Hardware Serial on pins 0 & 1
  //         to prevent communication conflicts with the ST Shield communications
  //*****************************************************************************
  st::Everything::debug=true;
  st::Executor::debug=true;
  st::Device::debug=true;
  st::PollingSensor::debug=true;
  st::InterruptSensor::debug=true;
  
  //*****************************************************************************
  //Initialize the "Everything" Class
  //*****************************************************************************
  
  //Create the SmartThings Thingshield Communications Object based on Arduino Model
  #if defined(ARDUINO_AVR_UNO) || defined(ARDUINO_AVR_NANO) || defined(ARDUINO_AVR_MINI)   //Arduino UNO, NANO, MINI
    st::Everything::SmartThing = new st::SmartThingsThingShield(pinRX, pinTX, st::receiveSmartString);      //Use Software Serial
  #elif defined(ARDUINO_AVR_LEONARDO)  //Arduino Leonardo
    st::Everything::SmartThing = new st::SmartThingsThingShield(&Serial1, st::receiveSmartString);  //Use Hardware Serial
  #elif defined(ARDUINO_AVR_MEGA) || defined(ARDUINO_AVR_MEGA2560)  //Arduino MEGA 1280 or 2560
    st::Everything::SmartThing = new st::SmartThingsThingShield(&Serial3, st::receiveSmartString);  //Use Hardware Serial
  #else  
    //assume user is using an UNO for the unknown case
    st::Everything::SmartThing = new st::SmartThingsThingShield(pinRX, pinTX, st::receiveSmartString);               //Software Serial
  #endif  

  //Run the Everything class' init() routine which establishes communications with SmartThings
  st::Everything::init();
  
  //*****************************************************************************
  //Add each sensor to the "Everything" Class
  //*****************************************************************************
  st::Everything::addSensor(&sensor1);
  
  //*****************************************************************************
  //Add each executor to the "Everything" Class
  //*****************************************************************************
  
  //*****************************************************************************
  //Initialize each of the devices which were added to the Everything Class
  st::Everything::initDevices();
  //*****************************************************************************
  
  //Set the lastStatus variable to force the LED update the first time through the loop()
  lastStatus = !sensor1.getStatus();
  
}

//******************************************************************************************
//Arduino Loop() routine
//******************************************************************************************
void loop()
{
  //*****************************************************************************
  //Execute the Everything run method which takes care of "Everything"
  //*****************************************************************************
  st::Everything::run();
  
  //Check to see if the Furnace is in Alarm.  If true, set the Smart Thing Shield
  //LED to Red.  If false, set the LED to Green.
  if (sensor1p->getStatus() && !lastStatus)
  {
      //ALARM!!! (Red)
      ((st::SmartThingsThingShield*)st::Everything::SmartThing)->shieldSetLED(2,0,0);
      //st::Everything::setLED(2,0,0);
      lastStatus = true;

  }
  else if (!sensor1p->getStatus() && lastStatus)
  {
      //NORMAL (Green)
      ((st::SmartThingsThingShield*)st::Everything::SmartThing)->shieldSetLED(0,2,0);
      //st::Everything::setLED(0,2,0);  
      lastStatus = false;
  }
  
}

```

**Comment by mikelupo** [comment]
Hi Dan,
I was traveling today and just sat down to catch up with you.
Yes, you indeed helped me with this sketch back in 2015. The furnace alarm has saved us at least 3 times while away. Once we were even in mexico! So I happen to have an extra thing shield from then (I had ordered two). So that’s why I’m using the old stuff and not a newer WiFi shield .

Anyway I’ll try this out now and will advise 

Thanks,
Mike

**Comment by mikelupo** [comment]
Hi Dan,
Thank you very much for your posts today.
The sketch indeed compiles and I have it running on the Arduino. When I shunt the pins 11 to ground the ThingSheild's LED goes from Green to Red. When I remove the shunt to ground, the LED goes back to green. Hardware seems to be working ok. 

The next level of debugging comes into play with the device handler. The ST_AnyThing_FurnaceAlarm device (Contact Sensor) type works just fine for the original furnace alarm. However, this new rendition of it, it does not. Seems to not detect closure versus open. In the Smart things app, it does show connected to the network, but it does not display any information regarding opened versus closed.

Curious where my suspicions should lie.

Thanks!

**Comment by ogiewon** [comment]
Please share a copy of that DTH so I can take a look at it.

**Comment by mikelupo** [comment]
Dan. It's working. 
The only disconnect was that the contact was named "contact1". My device handlers expected "contact"
Once I fixed that, it worked fine. 

Thanks for all your help today and listening.
I'll talk to you again in 2024. :)

**Comment by ogiewon** [comment]
Glad to hear it’s back up and running.  Have fun!
