### ISSUE TITLE
error: 'PinStatus' has not been declared (ST_Anything_Multiples_NANO33IoT)

### ISSUE THREAD

**Issue by rjelbert** [DanielOgorchock/ST_Anything#248]
Hi I am trying to compile the ST_Anything_Multiples_NANO33IoT sketch on Arduino IDE 1.8.15 and I am getting the error below. I can compile and upload other sketches on this board.

In file included from /Users/richardjel/Documents/Arduino/libraries/ST_Anything/PS_PulseCounter.cpp:43:0:
/Users/richardjel/Documents/Arduino/libraries/ST_Anything/PS_PulseCounter.h:65:103: error: 'PinStatus' has not been declared
    PS_PulseCounter(const __FlashStringHelper *name, unsigned int interval, int offset, byte inputpin, PinStatus inttype, byte inputmode, float cnvslope, float cnvoffset);
                                                                                                       ^~~~~~~~~
/Users/richardjel/Documents/Arduino/libraries/ST_Anything/PS_PulseCounter.cpp:69:118: error: 'PinStatus' has not been declared
  PS_PulseCounter::PS_PulseCounter(const __FlashStringHelper *name, unsigned int interval, int offset, byte inputpin, PinStatus inttype, byte inputmode, float cnvslope, float cnvoffset) :
                                                                                                                      ^~~~~~~~~
exit status 1
Error compiling for board Arduino NANO 33 IoT.

**Comment by ogiewon** [comment]
Thank you for the feedback.  I have uploaded new versions of PS_PulseCounter.h and PS_PulseCounter.cpp to the libraries\ST_Anything folder.  Please update your local copies of these files and try building again.

**Comment by ogiewon** [comment]
I also found that the latest version of the WiFi NiNa library is causing issues as well. Please revert to the WiFiNina v1.8.8 library.

**Comment by rjelbert** [comment]
Hi. Thanks very much for the updates. It now compiles and I can see sensor updates running by on the serial terminal. Great project and I'm hoping to get more into making Smartthings devices starting with an alarm unit. Cheers.
