### ISSUE TITLE
Will a ThingShield work with the Aeotec Smart Wifi Hub?

### ISSUE THREAD

**Issue by mikelupo** [DanielOgorchock/ST_Anything#251]
My V1 hub went offline as of July 1 (as all ST users who have V1 hubs are aware). I purchased the Aeotec Smart Home Hub (Gen 5). Now, I've had to exclude all of my devices and re-add them. This has worked ok with manufactured devices (i.e GE, Leviton, Schlage, etc). 
That being said, I cannot seem to add my Arduino Uno with Thingshield to the ST app. There is seemingly no support for it any longer.

Any ideas?

Thanks,
Mike

**Comment by ogiewon** [comment]
The ThingShield should still pair with the ST v3 hub, as well as the Aeotec ST hub.  Look at your hub’s details in the ST IDE (account.SmartThings.com) and check the Zigbee channel that is being used.  Some of the early SmartThings Zigbee devices seem to have trouble pairing when a high numbered Zigbee channel is selected. Try setting the hub to use Zigbee channel 20, and then follow the ThingShield reset and pairing instructions.

https://docs.smartthings.com/en/latest/arduino/

**Comment by mikelupo** [comment]
Currently channel 11. Setting to 20. Thanks for the link.
