### ISSUE TITLE
present not detecting

### ISSUE THREAD

**Issue by andrewvanlagen** [DanielOgorchock/ST_Anything#253]

**Comment by ogiewon** [comment]
Please describe the issue, or close this issue if you have already resolved it.

**Comment by ogiewon** [comment]
@andrewvanlagen - I am going to close this issue as there are no details.  If you want to add some details and reopen it, please feel free to do so.

**Comment by andrewvanlagen** [comment]
Is the a way to change the present time

**Comment by ogiewon** [comment]
No, there is currently no support for setting the date and time.

**Comment by andrewvanlagen** [comment]
Change dectect time in secs 
(Now it take around 5 - 10mins to detect presence not there )

**Comment by ogiewon** [comment]
Ahhh, that is a setting on the Parent Device in either SmartThings or Hubitat.  You can choose the amount of time to determine whether or not the microcontroller is 'present' or 'not present'.

**Comment by andrewvanlagen** [comment]
Ok i will try thanks

**Comment by ogiewon** [comment]
For example, in Hubitat you would change the following

![image](https://user-images.githubusercontent.com/5206084/133640468-5b1a6845-3696-4605-aedf-cd0a2b98e7ea.png)

**Comment by andrewvanlagen** [comment]
Thanks

**Comment by andrewvanlagen** [comment]
fixed thanks
