### ISSUE TITLE
voltage help

### ISSUE THREAD

**Issue by andrewvanlagen** [DanielOgorchock/ST_Anything#254]
can i use a XMPT101B type sensor
or how can i use this type of sensor in your code

**Comment by ogiewon** [comment]
@andrewvanlagen - unfortunately, ST_Anything does not support measuring high-frequency AC analog input signals.  What is your particular application for using the XMPT101B sensor?

**Comment by andrewvanlagen** [comment]
I want to monitor 120v

**Comment by ogiewon** [comment]
If you simply want to know if 120VAC is present or not, I’d recommend plugging in a simple 5VDC USB power supply (like a phone charger) and then simply monitor the low voltage DC signal to be able to determine is the 120VAC is present or not.

**Comment by ogiewon** [comment]
Closed due to inactivity.  Please feel free to reopen this issue if you'd like to discuss further.
