### ISSUE TITLE
Trying to run the ST_anything_alarmpanel_ESP8266Wifi but only getting 1 way communication

### ISSUE THREAD

**Issue by jtesmer** [DanielOgorchock/ST_Anything#39]
Hi!

Brand new to this, and only been trying for about a week.  I was able to follow instructions up to getting the sketch on my 8266, parent on my device list, and parents and children published on my device handlers.  On the iPhone, I get the device "Test 1" which I have configured with IP and MAC.  When I first start up the 8266 the serial console reports  Everything: adding sensor named contact1, etc.

When I refresh device refresh button using the iPhone, I get messages on the serial console showing the status of the 5 contacts, alarm and free memory.

The problem is no child devices are created, and no messages appear to be coming back when from the device when I look on live logging.  What should I try next?

**Comment by ogiewon** [comment]
Is your ST Hub and the ESP8266 on the same network (I.e. Subnet)?  

Is the MAC address of the ESP8266 entered into the device configuration in all uppercase and without any delimiters. 

Did you enter the hub's IP address into your sketch correctly?

Can you ping both the hub and ESP8266 from another computer on the same network?

**Comment by ogiewon** [comment]
Also, the port that the ST hub listens on cannot be changed.  Just making sure you didn't try to change it in the sketch.

**Comment by jtesmer** [comment]
Ha Ha!  Got it!  I had the IP of the smartthings hub off by one!

Now to screw around with the sketch and really get into trouble.

Thanks for your prompt reply.

**Comment by ogiewon** [comment]
Gad to hear it is working!  Have fun!
