### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by wdw42829** [DanielOgorchock/ST_Anything#4]
I'm trying to compile ST_Anything.  But, I get the following error:

ST_Anything:93: error: 'namespacest' does not name a type
 void setup()
 ^
exit status 1
'namespacest' does not name a type

**Comment by ogiewon** [comment]
Are you using a recent version of the Arduino IDE?  Do you have all of the libraries necessary?

**Comment by wdw42829** [comment]
I'm on Arduino IDE 1.6.6.  I only have the default libraries installed with Arduino, and all the libraries you put in ST_Anything.  What other libraries do I need?

**Comment by ogiewon** [comment]
No other libraries.   Everything needed is included in this GitHub repository.  Have you been able to get it to compile yet?

**Comment by wdw42829** [comment]
Unfortunately, no.  I gave up and recreated your code with manual instances of all the switches and motion detectors I had connected to the Arduino, both for the Sketch and Groovy side.  It's all working now, so I'm good.  But, there is something in your code that doesn't allow installation to work with the base 1.6.6 Arduino installation.

**Comment by ogiewon** [comment]
So, I tried setting up a clean Windows 10 system today.  Using Arduino IDE 1.6.6, I have problems getting ST_Anything to compile.  So, I removed it and installed Arduino IDE 1.6.5 and everything works as expected without errors.  I'll look into the issue, but for now, you should be able to use 1.6.5.  

This is the second time this year a release of the Arduino IDE has caused issues.  Very frustrating...

Glad you were able to get things working for your application.  And thank you very much for pointing out this issue!

**Comment by ogiewon** [comment]
So, the problem is definitely a bug in 1.6.6.  I installed the "Hourly Build" beta version of 1.6.7 and the compiler error is now gone.  Others have the same problem with 1.6.6 as seen here https://github.com/arduino/arduino-builder/issues/44.

Hope this helps!

**Comment by wdw42829** [comment]
Thank you!!  Since I have everything working now with what I hacked together, I'm not going to try to update to this.  But, if I ever need to do a big Arduino project again, I'll look this up.  Thanks for your help.

**Comment by wdw42829** [comment]
Closing.
