### ISSUE TITLE
Child devices not auto creating

### ISSUE THREAD

**Issue by rhamblen** [DanielOgorchock/ST_Anything#41]
After testing the NodeMCU, I've written some code and changed devices around.
Went to install and I am not getting any child devices created.
The Adrunio monitor and smartthings logs see temperature and buttons pressed and when I change settings these show in the device.
Ive tried uninstalling the parent and reinstalling but to no avail.

The Live Logging shows responses... 

> 13:59:46: debug [name:temperature1, value:22, isStateChange:false, displayed:false, linkText:Alarm Panel, descriptionText:Alarm Panel temperature1 is 22]
> 13:59:46: debug isChild = true, but no child found - Auto Add it!
>  13:59:46: debug Parsing: temperature1 22
>  13:59:43: debug [name:button, value:pushed, data:[buttonNumber:1], descriptionText:button 1 was pushed , isStateChange:true, displayed:true, linkText:Alarm Panel]
>  13:59:43: debug Parsing: button1 pushed
> 13:59:30: debug [name:temperature1, value:22, isStateChange:false, displayed:false, linkText:Alarm Panel, descriptionText:Alarm Panel temperature1 is 22]
>  13:59:30: debug isChild = true, but no child found - Auto Add it!

Is this all due to the background changes??
Any thoughts?

**Comment by ogiewon** [comment]
If you've removed the parent device completely, and recreated it, I don't know why the child devices would not be auto-created.  Did you modify any of the Device Handlers in any way?  The Parent DH needs the Child DHs to be exactly as I have them in Github, at least certain parts must be exact (you can tweak the non-sensitive stuff if desired.)

Sounds like you had it working originally, and then " I've written some code and changed devices around."  Can you explain what you changed?  Can you share your sketch file?

Happy to try to help but I need more information.

**Comment by rhamblen** [comment]
Hmmm went back to source code and it worked except for buttons.
serial monitor shows Smartthings gets sent a button command
> Everything: Sending: button1 pushed
> Everything: Sending: button1 held

in live log...

> debug [name:button, value:pushed, data:[buttonNumber:1], descriptionText:button 1 was pushed , isStateChange:true, displayed:true, linkText:Alarm Panel]

note this is using your sample code with just wifi details added.
so I have 8 of the 10 devices (child devices)

As the button presses are recognised (and when I move the button to contact or smoke it is also working fine) I am at a loss.

**Comment by ogiewon** [comment]
Buttons do NOT create Child Devices.  The Parent receives the Button "PUSHED" and "HELD" events and then broadcasts those events to any SmartApp that has subscribed to those events.

If you look at the Aeon Minimote Device Handler, you'll see it just has a single time with an Icon of a Remote Control on it.  There is nothing you can do with that tile.  Therefore, for ST_Anything, I did not do anything more.  I did at least add a tile to the Parent that shows how many button devices are defined.  

Go into the Smart Lighting App in the SmartThings phone app, add a new Lighting Automation, and use a button press or hold as the event trigger.  You will be able to select the ST_Anything Parent Device from the list displayed, and it you show you the button numbers based on what you defined for number of buttons in the parent's configuration screen.

**Comment by rhamblen** [comment]
OK thanks for clarifying this.
I was using rules engine and Core previously and I just didnt see the buttons this timaround to select so I wasnt sure what I was doing wrong.
I'll recheck but assume closed and thank for the help.

**Comment by ogiewon** [comment]
Great to hear it is working for you!  Have fun with it.
