### ISSUE TITLE
Cannot remove motion tile

### ISSUE THREAD

**Issue by shaiss** [DanielOgorchock/ST_Anything#5]
as soon as I comment out "standardTile("motion"" in the device handler groovy line 89, the "arduino thingshield" is removed from the app.  it seems like it's defaulting to a motion device, and therefore if there's no motion, no device.

Ay ideas what I'm missing here?

**Comment by ogiewon** [comment]
Did you also remove the reference to "motion" later in the same file?  Look at lines 126 and 127.

Dan

**Comment by shaiss** [comment]
Here's the code, I just removed the mention of motion on 1267 & 127 as well as commentted out the tile.  and the device disapeared from the app:
<iframe src="//pastebin.com/embed_iframe/g2pMjHe0" style="border:none;width:100%"></iframe>

**Comment by ogiewon** [comment]
It appears you commented out many more tiles than just "motion" based on the code you provided.  You will need to remove any commented out tile name from lines 126/127  (or 127/128 from your pastebin at http://pastebin.com/g2pMjHe0)

Dan

PS I just noticed that this reply is basically a year later...  sorry about that!
