### ISSUE TITLE
DHT library update

### ISSUE THREAD

**Issue by vseven** [DanielOgorchock/ST_Anything#72]
Newest stable version for both ARM + AVR processors (same as what you currently have but updated):

https://github.com/RobTillaart/Arduino/tree/master/libraries/DHTstable

New version optimized for AVR (which fixed some of my issues):

https://github.com/RobTillaart/Arduino/tree/master/libraries/DHTlib

Not sure if you could include both in your library and then in the PS_TemperatureHumidity files do a include based on processor architecture.  Like if ARM add in DHTStable and otherwise add in DHTLib or something like that.

**Comment by ogiewon** [comment]
Can't have both libraries in your local ...Arduino\libraries\ folder as it tends to confuse the Arduino Compiler/Linker (at least it used to!)

I used to have the optimized version of the DHT library, but then determined it was for ATMEL AVR Arduinos only.  So, I switched to the stable version which works with ARM and ATMEL processors.  I did this in order to support the ESP8266 boards.

**Comment by ogiewon** [comment]
I have updated my ST_Anything local copy of the DHT library to the most current "Stable" version.

**Comment by vseven** [comment]
I'm also going to do some research on including both....I have a feeling you'd have to rename one of them and then call out that one specifically which is unfortunate (like dth-avr.h and cpp and call it like that in the ESP32 sketches then leave the stable one alone to maintain compatibility) but I'll see if there is something automatic and if I find anything I'll post.

**Comment by vseven** [comment]
Did some research and posted on a C++ forum and got a hint that got me the answer.  Ended up being easier then I thought.  If you want to use both the updated/optimized library (for AVR) and the stable library (for ARM + AVR) here is what you can put in your PS_TemperatureHumidity.h file:

```
#ifdef ARDUINO_ARCH_ESP32
#include "..\DHTlib\DHT.h"
#else
#include "..\DHTStable\DHT.h"
#endif
```

Include the DHTLib and DHTStable like you include the other libraries and when compiling for a ESP32 it will use the optimized libraries and for everything else it should use the stable.  As time goes on and the ESP32 gets more mature I really think it will start overtaking the 8266 based on its abilities.  With that said if you are willing to include both libraries I'll put in all the pull requests for this.  If not I understand also.
