### ISSUE TITLE
ESP32 WiFi compile issues

### ISSUE THREAD

**Issue by vseven** [DanielOgorchock/ST_Anything#73]
So I downloaded a fresh copy of the ST_Anything libraries and I cannot get existing sketches to compile against a ESP32 when the disconnectCounter is a member variable.  I can get it to compile when the variable is defined within the cpp file but not in the header file like in my original commit.  I'm not sure why or if I'm doing something wrong.  I tried compiling against both a ESP32 DeV Module and a Node32s with the same error messages.

Moving it back to the cpp (whether right or wrong) allows it to compile and work properly.

**Comment by ogiewon** [comment]
Thanks for the feedback.  Looks like the code was modified without thorough testing.  Should be fixed now.  Please give it a try.

**Comment by vseven** [comment]
Yup, seems to work properly.  Thanks!
