### ISSUE TITLE
RGBW Control - Send W as part of Hex or seperate command?

### ISSUE THREAD

**Issue by vseven** [DanielOgorchock/ST_Anything#74]
So the RGB device seems to work well and sends a standard color HEX through the new childSetColorRGB command in the parent.  The question is for RGBW should it be a add on command called childSetColorRGBW or just a childSetWhiteLevel command?  I would think the latter just so the color HEX can remain the standard #RRGGBB instead of having to send it as #RRGGBBWW.  Either way its going to need another command (which is simple) and a new DTH that has a white level slider (already done...testing now).

Which would you guys prefer?

**Comment by ogiewon** [comment]
Good question.  I am partial to sending one command with all 4 values at once, personally.  This ensures that the Arduino code will get all of the values at the same time and can adjust the LED lights once, instead of twice.  The latter design might be noticeable to the human eye as two changes versus one single change.

**Comment by vseven** [comment]
Yeah, I'm just trying to keep it "standard" but I do understand since when pressing "on" it would send both the color and white level separately if it were two different commands.  

Ok....I'll store the white level as a device attribute (which is what the Fibaro does) and color (RGB) using the hex within the device as it currently is to maintain the standard but send to the device using "childSetColorRGBW" by combining the two and sending #RRGGBBWW.  

Now I have to figure out the dimmer since technically you can put the dimmer (for color) to 0% but still want the device to be one and do the white (which has its own slider).  I think I can figure that out....I'll push something this weekend.

**Comment by vseven** [comment]
Figured it out.  Little too many if then statements but it works.  Closing this and will post up the code over the next day or two.
