### ISSUE TITLE
Hub Version?

### ISSUE THREAD

**Issue by tjb8907** [DanielOgorchock/ST_Anything#9]
I tried finding this somewhere in the forum and your documentation, so I apologize if I'm blind and missed it, but does this only work on V2 hubs? or is it compatible with the original V1 hubs?

**Comment by ogiewon** [comment]
I have only tested the LAN-Connected (Ethernet and WiFi) with the SmartThings Hub v2.  The ThingShield worked fine on v1 hubs, but I upgraded a long time ago to the v2 hub.

I really don't know if it will work with a v1 hub or not.  Have you tried testing it?

**Comment by tjb8907** [comment]
I have not, and but I actually just ordered a v2 hub anyway so I am not going to mess with it until I get everything transitioned over.
