### ISSUE TITLE
Simple Usage Question

### ISSUE THREAD

**Issue by jrich523** [DanielOgorchock/ST_Anything#91]
So i'll start off by saying im not awesome with arduino but i am pretty decent at programming.

Im attempting to get the garage door setup working so I've followed the directions as best as possible and I've been able to get the unit up and running, with an IP and added in to smartthings with the devices available and apparently functioning.

I say apparently because according to the serial console its receiving and acting on commands but in the case of my garage door opener if i trigger it via the smart things app i see the serial monitor dump out state changes

Everything: Sending: doorControl1 closing
Everything: Sending: doorControl1 closed
Everything: Sending: doorControl1 open

It goes right back to open due to it being in a testing state on my desk (but it still sorta feels wrong), but from this i at least know that communication is all set.

So at this point I would expect to hear my relays trigger, but nothing.

For the code really all i did was rip out the unneeded stuff, essentially removing the pin variables and sensor interrupts.

//Define which Arduino Pins will be used for each device
//... RESERVED pins left alone
//Garage Door Pins 
#define PIN_DOORCONTROL_CONTACT_1 6  //SmartThings Capabilty "Door Control" 
#define PIN_DOORCONTROL_RELAY_1   7  //SmartThings Capabilty "Door Control" 
#define PIN_DOORCONTROL_CONTACT_2 8  //SmartThings Capabilty "Door Control"  
#define PIN_DOORCONTROL_RELAY_2   9  //SmartThings Capabilty "Door Control" 
...
  //Interrupt Sensors 
  static st::IS_DoorControl         sensor15(F("doorControl1"), PIN_DOORCONTROL_CONTACT_1, LOW, true, PIN_DOORCONTROL_RELAY_1, LOW, true, 1000);
  static st::IS_DoorControl         sensor16(F("doorControl2"), PIN_DOORCONTROL_CONTACT_2, LOW, true, PIN_DOORCONTROL_RELAY_2, LOW, true, 1000);

So these were how it was in the repo, so, no big deal wired it based off those pin numbers. I currently have both relays and one button on 6 (meaning door 2 wont have the correct state, but for testing i dont care)

If I press the button i added, i would have expected the door state to change from open to closed, but no go on that either and no serial output.

Am I foolishly assuming the logic for these types of devices are there some place or do I have to write the logic for it? based on reading the repo and stuff it sort of seems like i just need to clean up the code and wire it up and the challenge should be with getting it added to the smart things app.

Arduino Wiring
https://photos.app.goo.gl/tfHJCDkG5Bjl140o2

**Comment by jrich523** [comment]
just noticed my relays dont have a power light, which, doesnt make much sense, but hopefully thats my problem! will update soon

**Comment by ogiewon** [comment]
Sounds like your well on your way to debugging the circuit already.  Just in case, here is a pretty decent tutorial on wiring a relay up to an Arduino.  

http://howtomechatronics.com/tutorials/arduino/control-high-voltage-devices-arduino-relay-tutorial/

Please note that some relays are "Active Low" and others are "Active High".  Depending on which one you have, you may have to make a small edit to the Arduino Sketch.  Take a look at the ST_Anything source code for the IS_DoorControl.  At the top of the .h and .cpp files are the instructions for proper use of the device (attached below for quick reference.)  The last three parameters are really what drives the relay behavior.  Best to make sure these are set in a manner that keeps your garage door from opening or closing after a power blip to the Arduino.  We don't want any inadvertent state changes in the middle of the night!  I always power cycle my Arduino to make sure no undesired behavior occurs upon loss or restoration of power.  Safety 1st!  And Secruity a very close 2nd!

```
//			  Create an instance of this class in your sketch's global variable section
//			  For Example:  st::IS_DoorControl sensor3("doorControl1", PIN_CONTACT_DOOR_1, LOW, true, PIN_RELAY_DOOR_1, LOW, true, 1000);
//
//			  st::IS_DoorControl() constructor requires the following arguments
//				- String &name - REQUIRED - the name of the object - must match the Groovy ST_Anything DeviceType tile name
//				- byte pinInput - REQUIRED - the Arduino Pin to be used as a digital input
//				- bool iState - REQUIRED - LOW or HIGH - determines which value indicates the interrupt is true
//				- bool internalPullup - REQUIRED - true == INTERNAL_PULLUP
//				- byte pinOutput - REQUIRED - the Arduino Pin to be used as a digital output
//				- bool startingState - REQUIRED - the value desired for the initial state of the switch.  LOW = "off", HIGH = "on"
//				- bool invertLogic - REQUIRED - determines whether the Arduino Digital Output should use inverted logic
//				- long delayTime - REQUIRED - the number of milliseconds to keep the output on
```

**Comment by ogiewon** [comment]
Also, just saw your "button wiring" question...  You simply need to connect Arduino GND to Pin 6 or Pin 8 to  change the state of the door from Open to Closed.  These are designed to be routed through a typical magnetic door sensor (reed switch).  Something similar to these http://a.co/21J7Axk

**Comment by ogiewon** [comment]
Closing for now due to lack of activity.  If you still have any questions, feel free to comment here and we can re-open the issue.
