### ISSUE TITLE
Cant compile?

### ISSUE THREAD

**Issue by dookie454** [DanielOgorchock/ST_Anything#92]
I've had working Thingsshield for awhile now, and trying to find better Smartthigns control, came across this.  And I always seem to have problems getting Arduino code to compile from Github.  What do you think Im doing wrong?

I copied all of the Shield Library.zip and ST_Anything-master.zip to the Libraries and Sketches folder, and am running Arudino 1.8.5 as well.     Thanks for any help on this!  

Arduino: 1.8.5 (Windows 10), Board: "Arduino Mega ADK"

C:\Users\Main\Documents\Arduino\Sketches\ST_Anything_Multiples_Thingshield\ST_Anything_Multiples_Thingshield.ino: In function 'void setup()':

ST_Anything_Multiples_Thingshield:259: error: no matching function for call to 'st::SmartThingsThingShield::SmartThingsThingShield(int, int, void (&)(String))'

     st::Everything::SmartThing = new st::SmartThingsThingShield(pinRX, pinTX, st::receiveSmartString);               //Software Serial

                                                                                                     ^

C:\Users\Main\Documents\Arduino\Sketches\ST_Anything_Multiples_Thingshield\ST_Anything_Multiples_Thingshield.ino:259:101: note: candidates are:

In file included from C:\Users\Main\Documents\Arduino\Sketches\ST_Anything_Multiples_Thingshield\ST_Anything_Multiples_Thingshield.ino:65:0:

C:\Users\Main\Documents\Arduino\libraries\SmartThings/SmartThingsThingShield.h:140:3: note: st::SmartThingsThingShield::SmartThingsThingShield(HardwareSerial*, void (*)(String), String, bool, int)

   SmartThingsThingShield(HardwareSerial* hwSerialPort, SmartThingsCallout_t *callout, String shieldType = "ThingShield", bool enableDebug = false, int transmitInterval = 1000);

   ^

C:\Users\Main\Documents\Arduino\libraries\SmartThings/SmartThingsThingShield.h:140:3: note:   no known conversion for argument 3 from 'SmartThingsCallout_t {aka void(String)}' to 'String'

C:\Users\Main\Documents\Arduino\libraries\SmartThings/SmartThingsThingShield.h:92:8: note: st::SmartThingsThingShield::SmartThingsThingShield(const st::SmartThingsThingShield&)

  class SmartThingsThingShield: public SmartThings

        ^

C:\Users\Main\Documents\Arduino\libraries\SmartThings/SmartThingsThingShield.h:92:8: note:   candidate expects 1 argument, 3 provided

exit status 1
no matching function for call to 'st::SmartThingsThingShield::SmartThingsThingShield(int, int, void (&)(String))'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by dookie454** [comment]
I fixed it on my own!  lol.     Noticed the error line was not commented and setup for UNO,  so I changed Board type to UNO and it compiled.   Thanks!!!!!!

**Comment by ogiewon** [comment]
Remove the old SmartThings ThingShield library and only use the version from my repo.
