### ISSUE TITLE
Thingsshield - Dont see functioning buttons on phone 

### ISSUE THREAD

**Issue by dookie454** [DanielOgorchock/ST_Anything#93]
Loaded everything on an Uno, no errors, I only see "Refresh, Configure, and text called "1 buttons" because that's all I loaded on the seetings on App.   Configure doesnt do anything.  

I previously had Thingsshield running on the uno but with totally different code (examples online).

thanks

**Comment by dookie454** [comment]
All I see in Serial Monitor is "Setup..."

**Comment by dookie454** [comment]
and finally "Received Message; "" 
When I hit REFRESH, that comes through.  
When I hit Configure, that comes through as Refresh.   I dont see any buttons,  just text that says "1 button"

**Comment by ogiewon** [comment]
What sketch are you running?  Your old one?  If so, you'll probably need to rename your devices to comply with the new naming standard.  Only then will the child devices be created automatically during a refresh.

**Comment by dookie454** [comment]
RUnning the new one, the one called "ST_Anything_Multiples_Thingshield".    Should I be adding a child device from the Repo?  I added just the "Parent_ST_Anything_Thingshield".  

I guess I dont understand yet how this is supposed to work.

**Comment by vseven** [comment]
Yes, you need to add each child device you plan on using or for ease of use just add them all.

**Comment by dookie454** [comment]
where?  I just added two child devices in device handlers "Child Switch" and "Child Relay Switch" thinking they are simple Analog or digital inputs/outputs and dont see anything change in the phone app..  still shows the three "Refresh",  "Configure",  and "3 Buttons" text.   nothing changed.

**Comment by vseven** [comment]
Correct....you add then into your IDE as device handlers.  Then if you open up Logging and click refresh in the app you should see whats going on and any error messages.

**Comment by dookie454** [comment]
I changed the Device Handler for Thingshield to "Child Switch" and I get 1 switch icon in the phone app,  but it doesnt do anything, no response from Arduino Serial monitor.    Im not understanding where to make the changes and  how to add more than one, or how to get them linking on the arduino.    Where is logging?    BTW thanks for such fast responses!

**Comment by vseven** [comment]
I'm not sure what you mean....you changed the device type after it was installed to something else???

**Comment by dookie454** [comment]
In Smartthings Web Page/My Devices/Arduino ThingShield/Edit you change the "Type" to whatever you want it to use.   If I do that I see thigns like Child Relay Switch and whatever I added from your repo.  That shows up on the phone app after hitting UPDATE.

**Comment by dookie454** [comment]
Now I loaded a different sketch where I was getting responses from REFRESH..  I tried to go back to "ST_Anything_Multiples_Thingshield.ino" and I get these errors.. so maybe I never had it loaded?  This is on an Uno and Ide 1.8.5 since I thought Uno might be the easiest.  I do have a mega..

**Comment by vseven** [comment]
If you are changing the device type AFTER you already installed it then you are doing something very wrong.

I suggest deleting the device and following the instructions starting here:  https://github.com/DanielOgorchock/ST_Anything#smartthings-ide-setup-instructions  

You are definitely missing something.

**Comment by dookie454** [comment]
I was just changing the device type since nothing was working.  It may have not been working since the Uno wont load the code.  The MEGA does no problem.. but.. I have to pay with wiring to make the shield work on Mega and was trying to avoid that.   Ok I will start over following that guide and probably take the time to make the MEGA work since it loaded the code no problem.   Thanks for the help!!

**Comment by dookie454** [comment]
ok I got the MEGA and ThngsShield working with the Smarthings example code by changing the pin to 10 from 3 and added the jumper..   now Im kinda back were I was.. I see a bunch of sensors updating on the Arduino Serial window,  but still have just the 3 same iconds in the Phone app under Arduino Thingshield, with the "Parent_ST_Anything_THignsshield set as Type in "My Devices".   Where do I go from here?   The link doesnt really say.

**Comment by ogiewon** [comment]
The UNO does not have enough memory to run the full ST_Anything_Multiples_ThingShield sketch.  Pretty sure the comments at the top of the sketch even state as much.  

Are you in the US?  If so, simply add all of the CHILD device handlers via the Github integration.  It will make your life much simpler moving forward, and will ensure the example works as designed.  

The Child Devices are created by the Parent Device Handler code based on what is defined in the sketch.  Please do not rename the text names of the devices in the sketch, as there is a naming convention which must be adhered to.  

All of this is in the ReadMe in the repo...

**Comment by dookie454** [comment]
yes,  i understand all of that.  your stock arduino code is on mega except the rx pin changed and jumpered to 10,  and all parent/child added in device handlers,  then the main parent selected as type in Device List/Arduino Thingsshield...  then thats kinda where durections stop.  What should I be seeing?   How do i make an app device showing any/all data?  or how to control a digital output from the app?

**Comment by vseven** [comment]
That's the thing, if the shetch is set up correctly and all the child handlers are there and you entered the MAC address correctly (all caps, no delimiters) then all of the child devices will be created automatically. 

Go into live logging from the IDE and then try clicking that refresh button. A bunch of things will pop up in the logging that should tell you what is wrong.

**Comment by ogiewon** [comment]
You must jumper the MEGA per my ReadMe instructions. You can't use pin 10. Please follow the directions for wiring pins 2/3 to pins 14/15 to get the HW Serial comma working on the MEGA. This is the problem!!!

Allan - He's using a ThingShield, so no network config necessary as it uses Zigbee.

**Comment by ogiewon** [comment]
Per the "SmartThings" library ReadMe...

> 
You will need to wire the MEGA's HardwareSerial port's pins to pins 2 & 3 on the ThingShield. For example, using Serial3, wire Pin 2 to Pin 14 AND Pin3 to Pin 15.

**Comment by dookie454** [comment]
ok,  this I did come across one time but then couldn't find the info when I
went searching again...  closest I could find was the standard Pin3 to 10
swap...   thank you.  I will try later.     So no code changes are required
when adding the two wires for Mega to shield?

**Comment by ogiewon** [comment]
As long as you haven't modified any other part of the example sketch, no code changes.  The ST_Anything software automagically selects HW Serial3 when being compiled for a MEGA.  

For an UNO, it defaults back to the old Software Serial on pins 2/3.

**Comment by dookie454** [comment]
The updated serial wiring was the problem!!  SmartThingsSHIELD Pin 2 to
MEGA Pin 14,  and Shield 3 to MEGA 15 was the problem all along!     Now I
have tons of channels showing up.   Wow there are tons of options in some
of the items in the list..  I'll test it out tonight see how many things I
can get connected..     Thanks so much!!

**Comment by dookie454** [comment]
Is there any downside to renaming the "Display Name" in the Smartthings IDE
site from something like "Arduino Thingsshield (alarm1)" to "ST (Alarm1)"
 ?   Trying to get them shorter to see the names.

Thanks

**Comment by ogiewon** [comment]
Within the SmartThings app on your phone, you can rename every child device to whatever you want.  I have never tried renaming them from within the ST IDE.

**Comment by dookie454** [comment]
I renamed them in the IDE, it appears to still work ok.

As far as the DH22 sensor (everything else is straightforward analog
conection) how so I wire that?   All I found in the ARduino code are
this... but the DHT22 is one wire output digitial sensor so Temp and
Humidity come out over one pin and the DHT library decodes it.   I dont see
any of that code in the IDE, but the code appears to call out 3 data pins
for 2 sensors?

static st::PS_TemperatureHumidity sensor5(F("temphumid1"), 60, 40,
PIN_TEMPERATUREHUMIDITY_1,
st::PS_TemperatureHumidity::DHT22,"temperature1","humidity1");
  static st::PS_TemperatureHumidity sensor6(F("temphumid2"), 60, 50,
PIN_TEMPERATUREHUMIDITY_2,
st::PS_TemperatureHumidity::DHT22,"temperature2","humidity2");

**Comment by dookie454** [comment]
well I found a pin called for the DHT22 sensor on PIN 22,  connected it,
and I think the Arduino is reading the temp, but the ST APP Temp and
Humshow as -1.   Also the serial monitor shows something about the library
reporting DHT Time Out Error.

First time through Humidity)
First time through Termperature)
Everything: Sending: temperature1 77.36
Everything: Sending: humidity1 30.60
PS_TemperatureHumidity: DHT Time out error

**Comment by dookie454** [comment]
ok I removed everything from both sides, arduino and ST IDE,  reainstalled, repaired the ST Sheild.. and Wholla.  I have temp/hum readings on my phone.

Thanks guys!!  Good stuff!

**Comment by ogiewon** [comment]
Glad to hear it is working.  Have fun!
