### ISSUE TITLE
Cannot add device handlers through smartthings ide

### ISSUE THREAD

**Issue by perivar** [DanielOgorchock/ST_Anything#99]
After the update just a few hours ago the method of adding smartthings device handlers through the github integration is now empty.
Ie this does not work any longer:
	• Click on "Settings" from the menu and add my GitHub Repository to your account
		○ Owner: DanielOgorchock
		○ Name: ST_Anything
		○ Branch: master
		○ Click on "Update From Repo" from the menu
		○ Select "ST_Anything (master)" from the list
		○ Select all of the Parent and Child Device Handlers
		○ Check the "Publish" check box and click "Execute Update"
		○ You should now have all of the necessary Device Handlers added to your account

**Comment by perivar** [comment]
I didn't mention that the problem is that nothing comes up in the selection box where the device handlers used to show up so nothing can be added.

**Comment by perivar** [comment]
Now suddenly it started working again!? Closing the issue.

**Comment by perivar** [comment]
I don't know what is happening, but now it's gone from the SmartThings IDE again.
![image](https://user-images.githubusercontent.com/942356/34641232-364bd5de-f301-11e7-9d03-11d96d357349.png)

**Comment by perivar** [comment]
I just noticed that I have confused the device handlers and the smart apps. So nothing is wrong :)

**Comment by ogiewon** [comment]
Been there, done that! :)
